icpctools/icpctools

.gitlab-ci.yml
website/scripts/populate-releases.py

This will use the main repository for the releases.
My script that uploads ZIP's to the old releases is still running for a while but when it is done and we have merged this, we can get rid of the `build` repo.
I also fixed that the .gitlab-ci.yml will now get the version string from `version.properties` so we have only one place where it is stored.

Use main repository for releases.

---

website/content/changelog.md
website/layouts/shortcodes/toolblock.html
website/layouts/shortcodes/tooldownload.html

Fix typo, reduce 'version' to 'v' in several places, and reduce the number of times it uses the tool name.

Improve website text

---

CDS/README.md
CDS/WebContent/WEB-INF/jsps/freeze.jsp
CDS/WebContent/WEB-INF/web.xml
CDS/config/tomcat/conf/config/cdsConfig.xml
CDS/config/tomcat/conf/tomcat-users.xml
CDS/config/wlp/cds/config/cdsConfig.xml
CDS/config/wlp/cds/server.xml
CDS/config/wlp/cds/users.xml
CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/service/ContestWebService.java
CDS/src/org/icpc/tools/cds/util/Role.java

Create a new role for teams to log into the CDS or use REST services.
Notes:
- Defining a team user, password, and role are identical to other users. cdsConfig.xml has been updated to allow mapping from team login user name to the team's id in the contest(s).
- There was some mock team contest code in ConfiguredContest from a previous test of the ability to support this. I've rewritten that to not be hard-coded and create the team's contest (view) when it is defined in the contest.
- Teams now have access to the correct data - their own judgements and clarifications.
- I simplified getContestByRole(String) to a boolean because it was only being used in one place/purpose (verifying freeze). It cannot handle the team role (and doesn't need to) so better to simplify and make this obvious.

Add team role & login

---

CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/ConfiguredContest.java
ChangeLog.md

15 minutes later and I already thought of an obvious improvement: if there is no login for a team, don't bother creating a contest view for it. Although the memory bump per team is small, this means no change from 2.2 if you aren't adding team logins, or less memory use if you aren't creating logins for every team in every contest.
Also realized I can update the changelog for 2.3!

Don't create contest view if no login exists

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

The resolver logs to one of three log files to make it easy to have client and server running on the same machine and view the logs - but b/c option parsing happens before this you would see output like "Option found: --speed 0.3" on the command line. Reordering where this happens to avoid log file escapes.

Reorder log file setup and option parsing

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/JSONParser.java
ContestModel/src/org/icpc/tools/contest/model/feed/JSONWriter.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

First commit to support POST for submissions. RESTContestSource is updated to provide a method to perform a submit against a Contest API that supports it and the CDS' ContestRESTService supports POST by team or admin. The CDS acts as a simple proxy to the CCS.
Some details may need to be tweaked based on the final spec, but this has been tested with a local client able to submit to either the CDS or a temporary DOMjudge instance.

Support submission interface

---

PresAdmin/src/org/icpc/tools/presentation/admin/internal/DisplayConfig.java
PresCore/src/org/icpc/tools/presentation/core/DisplayConfig.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

When I was working on the last PR I noticed that the presentation window wasn't covering the full screen on a display that Windows was scaling. After a bit of digging and trial and error I've found how to correctly scale the window.
At the same time I fixed a separate bug: the display config to use the max screen resolution (e.g. "--display 1x") wasn't working on Windows because it requires you to enter full screen exclusive mode before setting the display mode. I switched the order of those.
I also added calls to (re-)create the background buffer strategy after changing the display - this is most likely overkill, but felt safer.
One big caveat: Windows scaling can only be used on the primary display. Based on testing, stack overflow, and googling, there is no way to support a secondary …

Handle Windows scaling

---

PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/TeamUtil.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/AbstractTileScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileListScoreboardPresentation.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Currently the ability to override the default team naming behaviour (usually the team's display name) is only visible as an option to the resolver. Due to some issues at a regional we want to enable this in the other tools and give a more wide open way to specify the name.
- Change style to a string.
- Change from enum of options like team_name to string substitution like "{team.display_name} - {org.name}". {team.name} and {org.formal_name} are also supported.
- Give a better way of setting the default (vs setting on every presentation) and use it in the resolver.
- Enable --style option in both presentation clients (matching what the resolver had).
- Fix up all the dependent presentations.
Readme updates will follow...

Team display style improvements

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
Resolver/src/org/icpc/tools/resolver/Resolver.java

Due to issues at the PacNW I'm adding (back) the ability to filter a contest by problem labels, undocumented for now. This will allow someone to run the resolver on a subset of a contest based on regex of the group ids and problem labels, e.g.:
--groups 123|125 --problems A|B|C

Ability to filter resolver by problem

---

Resolver/src/org/icpc/tools/resolver/awards/Awards.java

Fixing two bugs in the awards command line tool: --scoreboard isn't parsed correctly because the expected type of the arg is missing, and it doesn't handle the .xml vs .json file name correctly when picking the output file name

Fix award cli --scoreboard and output filename

---

Resolver/src/org/icpc/tools/resolver/TeamAwardPresentation.java

A few years ago we changed the team award presentation from using the ICPC logo to the contest logo from the REST feed. However, John has had a couple contests now that don't have a logo and the screen is blank, so let's add a second backup and bring back the ICPC logo if there is no contest logo.

Second backup for team award presentation

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/ContestData.java

The contest model (ContestData) is optimized for fast lookup and additions. While debugging a problem for John I found that in some edge cases (e.g. large contest, with run info, filtering down to even half the teams) the performance was awful, adding a full minute to the resolver startup time.
I finally bit the bullet and added a proper bulk delete operation. There is probably still a better way to do it or optimize, but this cuts the same 60s operation down to 6-7s.

Improve performance when deleting many contest objects

---

PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

Recreating the buffer strategy seems to cause issues on some OSes due to race conditions and when the peer hasn't been created. Since it was added recently and doesn't appear to be strictly necessary, I'll remove it.

Don't recreate buffer strategy

---

.gitlab-ci.yml

Also use the `needs` keyword to run some jobs in parallel.

Fix CI by only running jobs when previous ones succeeded.

---

CDS/WebContent/WEB-INF/jsps/layout/head.jsp
CDS/WebContent/js/contest.js
CDS/WebContent/js/ui.js
CDS/src/org/icpc/tools/cds/ConfiguredContest.java

Fixed a few indirect items:
- Admin-only navigation options (e.g. pres admin, video support) are now hidden until you log in as an admin.
- Basic post support for submissions and clarifications added to JS API (but not exposed on web).
- Fix to ui.js - noticed that clarifications were not being converted to well-formed html.
- Fixed missing pres-admin role and added team id to the output for team role (shows up at top-right on web).

Steps toward improved team support

---

CDS/WebContent/WEB-INF/jsps/details.jsp
CDS/WebContent/WEB-INF/jsps/details/clarifications-admin.html
CDS/WebContent/WEB-INF/jsps/details/clarifications.html
CDS/WebContent/WEB-INF/jsps/details/contest-admin.jsp
CDS/WebContent/WEB-INF/jsps/details/contest.jsp
CDS/WebContent/WEB-INF/jsps/details/groups-admin.html
CDS/WebContent/WEB-INF/jsps/details/groups.html
CDS/WebContent/WEB-INF/jsps/details/judgementTypes-admin.html
CDS/WebContent/WEB-INF/jsps/details/judgementTypes.html
CDS/WebContent/WEB-INF/jsps/details/languages-admin.html
CDS/WebContent/WEB-INF/jsps/details/languages.html
CDS/WebContent/WEB-INF/jsps/details/orgs-admin.html
CDS/WebContent/WEB-INF/jsps/details/orgs.html
CDS/WebContent/WEB-INF/jsps/details/problems-admin.html
CDS/WebContent/WEB-INF/jsps/details/problems.html
CDS/WebContent/WEB-INF/jsps/details/teams-admin.html
CDS/WebContent/WEB-INF/jsps/details/teams.html
CDS/WebContent/WEB-INF/jsps/layout/head.jsp

I created a team version of the UI that doesn't have API http links and 'admin-y' things like element ids. I don't _love_ this change, but I couldn't come up with a cleaner way to do this without creating copies of several files - although the UIs are close, I think you'd end up with a lot of if statements and odd logic to handle the number of columns and other differences.
Here's what I did:
- Removed the Overview page for teams in addition to the others. This is really just a 'connection details' page, so maybe it should be renamed even for admins.
- Removed the 'contest.setContestId()' from as many pages as possible and renamed them from .jsp to .html to be clear that they're now 'clean' client-side code.
- Renamed most existing /details pages to -admin and created a second copy of …

First pass at team (non-admin) web UI

---

CDS/WebContent/WEB-INF/jsps/layout/head.jsp

It seems to crash if you have no local and no remote contest source defined.

Fix crash when using default cdsConfig.xml.

---

CDS/WebContent/WEB-INF/jsps/details/teams-admin.html
CDS/WebContent/WEB-INF/jsps/details/teams.html
CDS/WebContent/WEB-INF/jsps/scoreboard.jsp
CDS/WebContent/WEB-INF/jsps/submissions.jsp
CDS/WebContent/js/contest.js
CDS/WebContent/js/model.js
CDS/WebContent/js/ui.js

Changed the Scoreboard (just problem header) and Submissions page (both judge queue and list of submissions) from server-side (jsp) to client-side (javascript) logic. This doesn't make either page completely 'clean', but it moves the bulk of the logic over. This will make it easier later to dynamically refresh parts of the page or reuse the pages when pointing at another Contest API server.
Minimal UI differences, and where there are it's more consistent with other pages (e.g. there was a footer on the judge queue that said how many there are, now it uses the card-tool at the top-right like everything in the Details page).
I didn't specifically test performance, but this page has always been slightly slower than other pages (due to sheer complexity compared to other pages) and even …

Move scoreboard and submissions pages toward client-side logic

---

CDS/WebContent/WEB-INF/jsps/layout/head.jsp
CDS/WebContent/WEB-INF/jsps/login.jsp
CDS/WebContent/WEB-INF/jsps/welcome.jsp
CDS/WebContent/css/cds.css
CDS/WebContent/js/theme.js
website/themes/icpctools/layouts/_default/baseof.html
website/themes/icpctools/static/js/theme.js

Since @meisterT likes screenshots:
I also updated the website to have a dark layout, but there you can not switch; it will use the browser setting ([if your browser supports it](https://caniuse.com/?search=prefers-color-scheme)).
On the CDS it uses the browser based setting as default, but you can change it if you want. It will store it in the local settings, meaning it will persist for the current host indefinitely (unless you clear your local storage).
At first I had the theme menu as a submenu of the user menu, but that was not very logical I think. And we have more than enough space.

Add support for AdminLTE 3.1 dark mode

---

CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
CDS/WebContent/WEB-INF/jsps/submissions.jsp
CDS/WebContent/js/contest.js
CDS/WebContent/js/ui.js

Added refresh icons to submissions and clarifications tables. When you click the entire card is overlayed with a spinner until the refresh is complete (which is often too quick to see for clarifications, noticeable for submissions).

Inline table refresh

---

CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
CDS/WebContent/WEB-INF/jsps/registration.jsp
CDS/WebContent/js/types.js
CDS/WebContent/js/ui.js

- Move <img> out of types and into template and make sure it looks ok when there are no logos.
- Only show one org column in teams table, not both org name and formal name.
- Minor alignment and UI fixes.
- Switch to dark overlay when reloading. Looks much better in dark mode, and only slightly worse in light mode.

Minor UI tweaks and logo updates to registration page

---

Resolver/src/org/icpc/tools/resolver/TeamAwardPresentation.java

If teams had a medal but no solution award, we show how many problems they solved.
However, we used the same award ID for all, meaning that if some teams solved X and some solved Y, it would show as X for all teams.
@deboer-tim I do wonder if we need to rename OTHER to SOLVED (and use a sovled-.* regex) to make sure it's unique if we add other awards at some point?

Fix "solved zzz problems" award.

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/WEB-INF/jsps/details-admin.jsp
CDS/WebContent/WEB-INF/jsps/details.jsp
CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
CDS/WebContent/WEB-INF/jsps/registration.jsp
CDS/WebContent/WEB-INF/jsps/scoreboard.jsp
CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
CDS/WebContent/WEB-INF/jsps/submissions.jsp
CDS/WebContent/js/contest.js

Change the contest.js to a proper class. This will allow some pages like the welcome page to connect to multiple contests at the same time and creates a better interface for clients. I also started using => to simplify the code.
This means we no longer support IE and currently 5% of the worldwide browsers according to https://caniuse.com/?search=class. This is unfortunate, but this is the cleanest and correct way to clean up the contest support for future and that number should be dropping.

contest.js class

---

CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/WEB-INF/jsps/details-admin.jsp
CDS/WebContent/WEB-INF/jsps/details.jsp
CDS/WebContent/WEB-INF/jsps/layout/head.jsp
CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
CDS/WebContent/WEB-INF/jsps/registration.jsp
CDS/WebContent/WEB-INF/jsps/scoreboard.jsp
CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
CDS/WebContent/WEB-INF/jsps/submissions.jsp
CDS/WebContent/js/contest.js
CDS/WebContent/js/ui.js
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

This change adds the current contest time to the top right of all the main screens: details, registration, submissions, clarifications, and scoreboard.
- The round trip time of every contest http call is halved, compared against the server's current time in the response, and the last 3 of these are kept as an average to determine the client time offset.
- The server's time comparison uses a CDS-specific 'ICPC-Time' header (ms accuracy), or falls back to the standard Date header (~second accuracy).
- The text handles when the start time is not scheduled, countdown is in progress or paused, normal contest time, and contest over.
- The CDS time multiplier is supported to show the correct clock when playing back contests at higher speeds.
- The one thing that is *not* handled yet are …

Add contest time to web pages

---

CDS/WebContent/WEB-INF/jsps/details-admin/languages.html
CDS/WebContent/WEB-INF/jsps/details/judgementTypes.html
CDS/WebContent/WEB-INF/jsps/details/languages.html
CDS/WebContent/js/types.js
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/ILanguage.java
ContestModel/src/org/icpc/tools/contest/model/internal/Language.java

Tested with a recent DOMjudge commit that contains this feature.
Screenshots:

Add entry_point_* and extensions fields to language.

---

CDS/src/org/icpc/tools/cds/presentations/PresentationFilesServlet.java
CDS/src/org/icpc/tools/cds/service/ContestWebService.java
CDS/src/org/icpc/tools/cds/util/HttpHelper.java
CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java

I noticed that Safari wasn't always loading org images. In the Web Inspector is looks like it's never getting a response, but on the server side you can see a setError(SC_NOT_MODIFIED) getting sent back. I didn't hook up a proxy to confirm, but this incorrectly includes the error page response in the body (like a 404) and I think that's what's messing up Safari. With this fix I've run several times and Safari is loading images correctly.

setStatus() when not modified

---

PresContest/src/META-INF/presentations.xml
PresContest/src/org/icpc/tools/presentation/contest/internal/nls/Messages.java
PresContest/src/org/icpc/tools/presentation/contest/internal/nls/Messages.properties
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/CommentaryPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TitledPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java

This is an initial commentary presentation as requested by Fredrik. This pass is functional and similar to a judge queue - commentary slides up from the bottom when they occurs, then fade away after a while - but is very vanilla. The messages are shown as-is, no formatting of teams or problems, text is not wrapped, etc. I'll follow up with visual improvements later.

Initial Commentary presentation

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

Fixes a problem where file references were set to null on objects that had multiple downloads. Cleans up the support in general by looking at local disk and syncing all files before trying to attach anything to the local contest object.
Also updates country_flag to the location that we went with in the CAF proposal.

Multiple file download

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/util/HttpHelper.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/SVGParser.java

API support for SVG images, as well as multiple file types per property (e.g. logos could be in png, jpg, or both). Notes:
- Formalized FilePatterns into a helper class that handles the standard differences between resources.
- Added svg mime type to file references and download header.
- Now use mime type when trying to pick local file name for files downloaded from CCS.
- Added SVG helper class to read the viewBox size out of SVG files.

SVG support for CDS (API)

---

PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/TimelinePresentation.java

Nit: when I playback contests at 10x or 20x speed, the 'current time' line in the timeline presentation wasn't tracking. Minor fix to update it.

Timeline not respecting time multiplier

---

ContestModel/src/org/icpc/tools/contest/model/internal/ContestData.java

If the array has been reduced to size 0 then you can never add items again, so fix the minimum size.

Fix array growth from 0

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

If there are no teams or no problems (possible in any broken feed, but more likely after using --groups or --problems with an incorrect id) the resolver should give an error and exit. Otherwise, it'll cause exceptions later.

Error if no teams or problems

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

There are currently 3 ways to load a contest (6 if you count XML vs JSON...): 1) HTTP URL/REST (with absolute or relative file references), 2) Disk/CDP/CAF (with local resources), and 3) directly from feed file (with no references, since this is mostly historic).
This switches the third method to use the REST contest source from the first, which means that if there are absolute file references in the feed then it should be able to download and use those. Relative URLs still won't work, since the behaviour is undefined and wouldn't match the CAF.
Also using this commit to slip in the one line change in DiskContestSource that was missing from previous commit.

Local feed + REST contest source

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/EventFeedContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

John hit an issue where an event feed didn't have a file extension and the code assumed it was xml. Reversing this everywhere so that JSON is the default and XML is only used when the file ends in .xml.

JSON by default

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

I wasn't planning on going this far, but one thing led to another...
- I started by trying to clean the code and avoid potential errors when pointing at an event feed file with absolute URLs.
- I did some general cleanup along the way - removing a couple unused methods, and making some private to make sure nobody is using/then can be inlined or removed as well.
- Changed every connection to go through the common createConnection() method - all URLs are either contest API (base URL relative) or simple contest sub-paths.
- Contest URLs were always cleaned to strip a trailing slash before, but Kattis has a redirect to include the slash. Now that's valid, and avoids an extra redirect on every API call.
- I noticed that you used to create the connection with a potentially bad URL and then …

REST connection cleanup

---

CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/js/contest.js
CDS/src/org/icpc/tools/cds/service/BasicAuthFilter.java
CDS/src/org/icpc/tools/cds/service/ErrorService.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

Return an error message in JSON format when a call to the API fails or the client device prefers JSON, following the same template as DOMjudge. Add the same support on the client side (both CDS -> CCS and web UI -> Contest API) so that they support error messages in both json and plain text formats.

JSON error messages

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

I noticed the CDS wasn't starting as fast as I thought it should, and found a 2s delay per contest waiting to connect to a REST contest source - even when loading from disk.
- Created a standard method to wait for contest load states and reused it across the other methods.
- Added one to wait for connection, and made the configured contest use it - but only for REST contests.
- Added some minor incremental backoff when the connection drops.
- Halved the number of output messages when loading from disk. Now if just shows 1 "imported" or one failure/not found message, before it would always show "importing" and potentially another message if there was an error or file not found. (not directly related, but it was bugging me while I was trying to debug this)

Avoid connection delay for disk contests

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/WebContent/js/cds.js
CDS/WebContent/js/types.js
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/service/ContestWebService.java
CDS/src/org/icpc/tools/cds/service/ResolverService.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/StartStatus.java

- Updated HTTP methods to match the new Contest API spec requirements.
- Updated cds.js and CDS admin page to support the same requirements.
- Added client-side support for modifying awards (but not implemented on CDS yet).
- Changed /resolver service to use JSON object encoding, fixed a bug where it wouldn't output anything if resolver hadn't been inited, and removed duplicate char encoding.
- Removed extra system.out from ContestSource (unrelated).
- Fixed bug in start status that would stop it from cloning correctly.

Update POST, PUT, PATCH, DELETE

---

CDS/src/org/icpc/tools/cds/util/HttpHelper.java

The character for full-width left quotation mark (`“`) cannot display correct in `head.jsp h1.m-0`.
Previously it was displayed as `&201c`. Then I found the `HttpHelper.sanitizeHTML(String s)` is not implemented correct before.
A probably fix is `&#8220;`, which doesn't require the hex converting.
BTW, there are many occurrence of unsanitized HTML. (e.g. `head.jsp li.has-treeview > a:first-child > p` is directly `<%= contest3.getName() != null ? contest3.getName() : "(unnamed contest)" %>`) Is the sanitization intended?

Fix unicode character sanitizing

---

ContestModel/src/org/icpc/tools/contest/model/feed/Timestamp.java

Currently, the timestamp string produced by CDS api is like `2014-06-25T11:22:05.034+01`.
However, in some browsers, this string cannot be parsed as Date, both in Firefox and Chrome.
If we extend the format be like `+01:00` it would work.
In Contest API standard, it said `timestamp` should be `yyyy-mm-ddThh:mm:ss(.uuu)?[+-]zz(:mm)?`. I think this change would be ok.

Fix Timestamp parse in frontend

---

ContestModel/src/org/icpc/tools/contest/model/feed/Timestamp.java
ContestModel/src/org/icpc/tools/contest/model/internal/ContestObject.java

PR 410 actually caused a regression handling some timestamps. To avoid making it even more complicated, I switched to using the Java 8+ API for time handling that can handle all cases.

Switch to DateTimeFormatter

---

CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
CDS/WebContent/js/types.js
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/ITeam.java
ContestModel/src/org/icpc/tools/contest/model/feed/XMLFeedWriter.java
ContestModel/src/org/icpc/tools/contest/model/internal/Award.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Team.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
Resolver/src/org/icpc/tools/resolver/TeamAwardPresentation.java
Resolver/src/org/icpc/tools/resolver/awards/AbstractAwardDialog.java
Resolver/src/org/icpc/tools/resolver/awards/EditAwardsDialog.java

This change handles two spec updates (because I'm lazy and they touched a couple of the same files):
- Teams can be hidden (will eventually replace group hidden flag)
- Award teamIds can be null (to signify the award hasn't been assigned yet)
Notes:
- If a team belongs to a hidden group then the CDS will automatically flag the team as hidden as well (in PlaybackContest), but nothing else does automatic conversion/migration. We should have a discussion on a future CLICS call to decide if any other compatibility is required. All of the ICPC tools use Contest.isTeamHidden() to check for hidden groups and this was updated to support hidden teams, so these tools shouldn't require any other changes.
- Column added to admin registration page to show hidden teams on the CDS.
- Null checks added …

Hidden teams and award null teamIds

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java

The logo generation utility fails if there are any empty org folders. This changes it to a warning and lists how many orgs were found. Ran into this while doing an initial edit pass for Moscow.

Logo generation warn for empty folders

---

build/cds/Docker/Dockerfile

This should fix the current build failure, but will also expire in a year. Next month we can update to JDK 17 release, which should be good for many years.

Update from OpenJDK 14 to 16

---

ContestModel/src/org/icpc/tools/contest/model/feed/Timestamp.java

Found some timestamps in older feeds that don't match the spec but the CDS was previously able to parse fine - single digit seconds or ms. Added these to the test and expanded the pattern to support.

Fix regression in timestamp parsing

---

ContestModel/src/org/icpc/tools/contest/model/IAward.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
ContestModel/src/org/icpc/tools/contest/model/util/messages.properties
Resolver/src/org/icpc/tools/resolver/awards/TemplateAwardDialog.java

Adds an award type that can be applied via template to the top x% of all teams. e.g. adding the following to the template dialog will give the top 25% of all teams an award that says "High honours": {"id":"top-25","count":25,"citation":"High honours"}.

Add top (%) award type

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
Resolver/src/org/icpc/tools/resolver/awards/AwardUI.java

Added a button to the Award UI named "Upload" that is only enabled when you're connected to a contest via REST. Clicking this button PUTs all awards to the server. This overwrites any of these award ids that exist (provided you have access) but does not affect any other award ids. As such there's a warning when you click the button and we need to decide what the options/behaviour should be long term.
To enable this I found it was more convenient to have post/patch/put/delete methods that accept a contest type + object instead of a json object. I also made the methods generic so they can accept any contest object. This means the methods can't have type-specific information, but that's covered in the spec and means we don't need separate methods for every type.
Also noticed that the top …

Award Util support for PUTing awards

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonUtility.java
CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/util/Taskbar.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/Admin.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
ProblemSet/src/org/icpc/tools/contest/util/problemset/ProblemSetEditor.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/awards/AwardUI.java

Application icons (e.g. on the dock on Mac) were missing for SWT apps. Not sure if it's a regression or how, but fixed this by using the same code that was being used for AWT apps. Made a common method in ContestModel - even though it's not the 'correct' place, it's one place where all apps can use it from.

Fix missing app icons

---

PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java

Fixed a regression in tile presentations, vertically centered emoji, and made the zero-width joiner stick with the current segment, since it could be used in normal text.

Minor emoji tweaks

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java

Am I happy with this code? No. Is it likely to require changes even in the next week? Yes. Cleanup afterwards? Are there some hardcoded bits? Absolutely.
The bulk of the change is reading directly into Contest API objects instead of the intermediate CMS objects that were there before. This means that you can import from .tsv or other formats, do any manipulation using standard mechanisms, and easily save to .tsv or .json formats. I had this part in a nice simpler commit but messed up my git history so it'll have to go in as one chunk now.

Support for reading config from 2020 CMS

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

Fixing the attribute filtering to match the proposed spec. This still goes one step further than the spec since you can filter by any (non-array) attribute, e.g. language=C.

Id attribute filtering

---

ContestModel/src/org/icpc/tools/contest/model/ITeamMember.java
ContestModel/src/org/icpc/tools/contest/model/internal/TeamMember.java

As per the last CLICS call, I am checking in the API to allow team-member video, desktop, backups, etc, for cases where each team member has their own machine, and it is known which team member is using which machine. We do not know how or if we'll be able to do the mapping for the 2020 World Finals (or if this is a one-off), but this provides the API in order to allow it.

Team member machine-specific API

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
Resolver/src/org/icpc/tools/resolver/SplashPresentation.java

Requested at finals 2019:
- Adding the version to the resolver splash screen. You can find this in the logs, but easier to be able to see if you're on the latest onscreen. Also added to the 'no presentation' client screen.
- Move the 'selected row' up by one so it's not quite so close to the bottom of the screen.

Show resolver version in splash, move selection up one

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

The unchanged 'TODO' in ResolverLogic 689 was bugging me, so I went back and fixed it properly - how to adjust the scrolling to account for how many teams are shown onscreen just shouldn't be in the generic resolver logic. I moved this to the UI side where it can correctly adjust for any changes.

Move resolver UI code where it belongs

---

ContestModel/src/org/icpc/tools/contest/model/util/ArgumentParser.java
PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java
PresCore/src/org/icpc/tools/client/core/BasicClient.java

This change does three things (because I'm lazy):
- Fixes an NPE regression when you don't specify any args to the tools.
- Outputs the help when you don't specify a contest or have an incorrect number of args.
- Switches the presentation client back to using a daemon thread, because ubuntu (see issue #323).

Client arg help and ubuntu fix

---

ContestModel/src/org/icpc/tools/contest/model/IAward.java
ContestModel/src/org/icpc/tools/contest/model/feed/XMLFeedWriter.java
ContestModel/src/org/icpc/tools/contest/model/internal/Award.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
ContestModel/src/org/icpc/tools/contest/model/util/messages.properties
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/TeamAwardPresentation.java
Resolver/src/org/icpc/tools/resolver/awards/AddAwardDialog.java
Resolver/src/org/icpc/tools/resolver/awards/EditAwardsDialog.java
Resolver/src/org/icpc/tools/resolver/awards/GroupHighlightAwardDialog.java
Resolver/src/org/icpc/tools/resolver/messages.properties

--bill was created a few years ago, and it amounted to two things:
1. Use judge queue for Honorable Mention teams.
2. Show a list for Honorable Mention teams and subsequent groups of teams that solve each consecutive # of problems (except medals).
We've talked about how to make it a bit more standard, and this is the first step of that, for #2. Up to now the award generator/resolver has used a boolean attribute on awards called "show" that was either false (just pause, then move on, e.g. for FTS) or true (stop and show the team detail, e.g. for medals). This change turns it into a string display_mode attribute that has three options: "detail", "pause" (the same two options as before) and "list". Any award that has this last option will wait until every team has been resolved and then show …

Start to standardize --bill

---

build/cds/Docker/Dockerfile
build/cds/Docker/start.sh

No JDK 17 available, maybe because we're on ubuntu:focal. Also switch order of admin/presadmin setting for issue #447.

Back to JDK 16

---

PresContest/src/org/icpc/tools/presentation/contest/internal/ICPCFont.java
PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/old/FloorNamePresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java

It was annoying me that the team intro presentation logos weren't always near the text and sometimes too wide for the screen. Improved the text helper to correctly handle alignment and scaling to fit within a specific bounds. Also improves text fitting on the scoreboard and tile scoreboard when names are too long.

Improve text fit when names are too long

---

PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/JudgePresentation.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/TeamListPresentation.java

- Changed team list to a single column with teams flying in from the bottom.
- Changed scoreboard highlight for lists to not outline every item.
- Changed text helper to use a layout (allowing potential reuse later) and draw all items based on their center position.
- Removed some old code and unnecessary user messages.

Team List presentation improvements

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java

Remove some unused methods, and make the video stream data static - which will allow it to persist across CDS config changes and avoid duplicating streams.

Streams handle config change

---

BalloonUtility/src/org/icpc/tools/balloon/Balloon.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/service/ReportGenerator.java
CDS/src/org/icpc/tools/cds/service/StartTimeService.java
ContestModel/src/org/icpc/tools/contest/model/internal/ContestObject.java
ContestModel/src/org/icpc/tools/contest/model/util/ArgumentParser.java
PresContest/src/org/icpc/tools/presentation/contest/internal/PresentationClient.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java

- new Integer/Long/Float/Boolean(String)
Deprecated and marked for removal.
Use parseInt/Long/Float/Boolean(String) to convert to primitives, or
valueOf(String) to create objects.
- new Long/Integer/Float(long/int/float)
Deprecated and marked for removal.
Use Long.valueOf(long/int/float). Auto-boxing usually compiles into this.
(see https://stackoverflow.com/questions/31445024/does-autoboxing-call-valueof )
- Class.newInstance()
Deprecated,
can be replaced by clazz.getDeclaredConstructor().newInstance().

Modernize use of deprecated methods to new ways

---

ContestModel/lib/BUILD
PresContest/src/BUILD
Resolver/scripts/resolver.bat
Resolver/scripts/resolver.sh
Resolver/src/BUILD

Following up the discussion in #402, I see that emoji SVGs have been implemented in 1833cd753c589c7cb935b7ee449d67235de246a5, thanks for that @deboer-tim! :smile: 
The emoji render fine when I run the resolver from IntelliJ, but when trying it from the built package, I got the following error:
```
$ ./resolver.sh ../event-feed-bapc/ --test
--- ICPC Resolver (2.4.582) ---
Log: logs/resolver_21.10.01_09.26.04.log
Unknown property ignored: awards/show
Test mode active, 0 unjudged submissions discarded.
Resolving 359 pending submissions out of the 1888 total submissions in the contest... 
Done resolving
Playback time: 11m 1s
Total pauses: 42
Error painting
java.lang.NoClassDefFoundError: com/kitfox/svg/SVGUniverse
at org.icpc.tools.presentation.contest.internal.TextHelper.loadEmojiFromFile(Tex …
```

Add SVG library to classpath of Resolver

---

PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

@troy2914 noted the error message was not very clear. Now it displays info on all connected screens.

Improve error message when supplying a wrong screen name.

---

ContestModel/src/org/icpc/tools/contest/model/internal/NetworkUtil.java

Noticed that on the contest floor we didn't report the correct IP address. This should fix it as long as you have one network interface. If you have more, it will report one of them.

Use network interfaces to look up local IP address.

---

PresContest/src/META-INF/presentations.xml
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/test/TestClockPresentation.java

Add a property to enable drawing of local time and time sync details,
and a visible 1 second sync line. When enabled, the server time diff
and local time are shown with a description. If the system nanoTime
and currentTimeMillis differs by more than a threshold, it is also
shown.

Add test clock drawing of local time and time sync

---

ContestModel/src/org/icpc/tools/contest/model/internal/Group.java
ContestModel/src/org/icpc/tools/contest/model/internal/Organization.java
ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
ContestModel/src/org/icpc/tools/contest/model/internal/Team.java

The org url and hashtag were being overwritten by the CCS. This fixes them by allowing null values to be overridden by default objects in PlaybackContest.

Fix attribute overriding by CDS

---

PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileScoreboardPresentation.java

- march tile gray color in header in both light and dark mode
- use dark orange for frozen contest time

Use lighter grays in light mode tiles presentation

---

ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
PresContest/src/org/icpc/tools/presentation/contest/internal/chart/ProblemDetailChart.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/CountdownPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/StatusCountdownPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/floor/BalloonFloorPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/floor/ContestFloorPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/BalloonMapPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileRankScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/core/chart/AbstractChartPresentation.java

Changes:
- Fixed countdown so it shows pause time even if opened after pause. EoC countdown now negative.
- Floor map presentations - move team logo over the chairs and improved colours.
- Balloon floor presentation - stop balloons at 2m instead of 98%, logo under balloons when small.
- Default contest location changed to Moscow.
- Light mode for charts, floor maps, etc

Presentation color/minor fixes

---

PresContest/src/org/icpc/tools/presentation/contest/internal/Legend.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScrollingScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/ScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/TimelinePresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

The main/old scoreboard header wasn't handling light mode because it was set after the header image was created. This makes sure it is set before setting the size or other methods. Also fixed the legend and made setProperty() always call the super first.

Fix scoreboard light mode

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java

When a group becomes hidden after the teams are created, the CDS doesn't support backward compatibility and make the teams hidden. This should fix that.

Hidden Groups -> Team

---

ContestModel/src/org/icpc/tools/contest/model/feed/JSONParser.java

Fredrik showed me a case where Kattis was outputting "null" for the decimal location attribute, but the CDS would interpret and export this as -1. This correctly reads as NaN, which will trigger the CDS to skip it on output.

Don't parse "null" location string as -1

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

I broke command line tools reading from a standalone event feed in PR #389. This was reported in issue #536. Instead of the fix suggested (undoing from REST to Disk source), I'm going all in.
In the beginning, there was a PC^2 source, then an XML socket source, then an XML disk source, and then a disk source that would read XML + logos... Then came JSON. At one point I counted something like 7 different ways that you could load contests, each of them was very different, and there were inconsistencies in all of them.
Now the only real/current sources are the Contest API, a contest archive, or a saved feed. Any of these could have a feed that contains relative or absolute URLs. We've already had requests to support a local feed that has absolute URLs requiring auth, which means you might …

Fix loading from local feed

---

build/cds/Docker/Dockerfile
build/cds/Docker/start.sh

Note that we use SDKMAN! to install Java for two reasons:
* Ubuntu does not have 17.0.1 yet and it seems that the open 17.0.0 on Ubuntu from the Ubuntu repo still crashes with the JNDI error.
* We can now more easily upgrade to any version or JDK we want.

Use Java 17 for CDS Docker image, which is now supported by the CDS.

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

Block the CDS from accepting PUTs on ids that are invalid, and have the admin UI automatically replace invalid chars with underscores

Avoid invalid contest object ids

---

CDS/WebContent/WEB-INF/jsps/scoreboard.jsp
ContestModel/src/org/icpc/tools/contest/model/IProblem.java
ContestModel/src/org/icpc/tools/contest/model/Scoreboard.java
ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
ContestModel/src/org/icpc/tools/contest/model/internal/Result.java

Changing scoring with the assumption that the current ccs-specs PR icpc/ccs-specs#64 will get accepted. Most of these will make sense either way:
- No assumption that scoreboard_type is in the scoreboard.json.
- Solved attribute is required for pass-fail contests; score for scoring contests.
- Clients (including CDS) no longer need to make assumptions about judgement default scores.
- Added problem max_score.
Also made test_data_count non-optional as per the spec.

Scoring fixes

---

ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestWriter.java
ContestModel/src/org/icpc/tools/contest/model/internal/MapInfo.java
ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
ContestModel/src/org/icpc/tools/contest/model/internal/Team.java
ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGenerator2020.java
ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorNAC.java

Fix regressions with floor map that Nicky reported, fix issues writing the extended MapInfo to disk, and break backward compatibility (figured it's a good time due to the floor map switch to json) to make problem location consistent with team.
- Team: remove support for old group_id, and standalone x/y/rotation attributes (they've been inside a location object for a few years). Add setLocation() helper.
- Problem: move x/y into a location object to match team, for addImpl() use switch statement instead of lots of ifs, make test data count optional again. Add setLocation() helper.
- ContestWriter: add support for writing singleton objects like State and MapInfo. (missed that before)
- MapInfo: change printer helper to be called setLocation to match others, and use the setLocation() …

Fix and update floor map

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

So NWERC uses the same CAF location for both Kattis and DOMjudge, but (of course) used different CCS URL's. The cache directories where the same so we had a event feed cache file again that was corrupted. This uses the CCS URL (if present) in the cache directory name, preventing this issue.

Allow two configured contests with the same CAF but another CCS URL.

---

ContestModel/src/org/icpc/tools/contest/model/internal/Commentary.java

The spec says problem_ids and team_ids can be null but we didn't support it properly. Now we do.

Allow team_ids and problem_ids to be null for commentary.

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/StatusCountdownPresentation.java

I noticed that statuses overlap on smaller screens or when text is really long, making text fit and improving the layout slightly.
P.S. Woo hoo, runs on M1 :)

Improve countdown status text fit

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

Correctly merge local file references with references that exist on an object. Currently, if an event feed has remote references they are wiped out after scanning the local file system; this will merge the lists, preferring local files when they have the same dimensions.
Also added toString() to file patterns for debugging.

Merge local and remote file references

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

My CDS gave an error if I had JSON's without logo's but then had logo's on disk. This fixes it, but I'll leave it to you to decide if this makes sense.

When current list is null or empty, use local list.

---

PresContest/src/META-INF/presentations.xml
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java

cc @niemela , who suggested this during NWERC.
This uses the same team intro presentation, but then uses it for organizations. Useful if you have multiple teams per org.
I tried it in the SWERC dataset. It *does* work, but since uni's are still pretty close in these contests, it doesn't look great. Maybe we later should improve that.
Note I had to call `setup()` again to re-set up the data. Changing the property while the presentation is running makes it flicker for a few ms, but I'm not sure if we can fix that.

Add option to use team intro presentation for organizations.

---

ContestModel/src/org/icpc/tools/contest/model/internal/YamlParser.java

SnakeYaml's default behaviour is to load any required Java classes that are found in yaml source with a particular syntax. Since we don't have any requirement for that 'feature', this change avoids loading those classes and hence also the potential security risk.

Avoid loading arbitrary code based on yaml

---

ContestUtil/src/org/icpc/tools/contest/util/cms/GoogleMapsGeocoder.java
ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java

- Actually use the paths you supply at the CLI instead of hardcoded paths. Also add argument for CMS contest root (for Person.tab/TeamPerson.tab files)
- Retry Google Maps API without country code if it does't work with country code. Example: Universidad de Murcia ESP vs Universidad de Murcia
- Add option to assign team ID's in order. Non-WF contests often have all teams have ID 0 in the CMS. If the contest doesn't care about actual numbers, this will assign 1- n to them

Improvements to the CMS importer:

---

CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java

Added filename to file references according to the spec update. This change is backward compatible.
- CDS sets the filename when loading from disk or creating files.
- When downloading files (tools connecting to CDS, or CDS connecting to a CCS) it uses the given filename and extension if it exists. Falls back to CAF patterns if the filename is missing or invalid.

FileReference filename

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/IGroup.java
ContestModel/src/org/icpc/tools/contest/model/IProblem.java
ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java

API support for problem package and statement (assuming my proposal for renaming the property is accepted - otherwise we'll rename later). Updated CDS so that it will automatically download and cache package & statement locally to ensure it can serve these to downstream users.
Fixed two minor issues with group that I noticed while implementing - Javadoc copy/paste from org and not automatically downloading group logos (a spec extension).

Support for problem package

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/video/VideoServlet.java

Avoid nginx buffering streaming responses. User could turn this off globally on nginx, but better they don't even have to know about it.

Add nginx non-buffering header

---

ContestModel/src/org/icpc/tools/contest/model/IAccount.java
ContestModel/src/org/icpc/tools/contest/model/IContest.java
ContestModel/src/org/icpc/tools/contest/model/IContestObject.java
ContestModel/src/org/icpc/tools/contest/model/internal/Account.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

Add new /accounts endpoint from Contest API. It refers to 'people_id' which makes no sense on the current CDS, but I figured it's marginally better to implement matching the current API and clean up any minor issues later.

Add Accounts endpoint

---

ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/util/ArgumentParser.java

If you provide an incorrect contest URL, the updated RESTContestSource was silently auto-connecting to the 'best' one. This could lead to you thinking you're connecting to 'dress' but actually connecting to 'finals'.
I've refactored the code to clearly deal with these cases:
1) Connecting to a contest URL (/contests/x): Should just work and never modify URL.
Connecting to ACM ICPC World Finals 2018 at https://localhost:8443/api/contests/backslash
2) Connecting to a Contest API root (/ or /contests): Pick the best contest, and tell you what it's connecting to:
Invalid contest source: Possible Contest API at https://localhost/api/contests but no contests found
or
Only 1 contest found, connecting to https://localhost/api/contests/finals - World Finals starting at 7:00.00 a.m. April 04, 2019 …

Fix RESTContestSource url matching

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestAPIHelper.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

It was bugging me that RESTContestSource is an API class, but has been outputting messages to the console and auto-connecting while it validates the URL. For some uses you may not want auto-connect or console output. Separated out a new ContestAPIHelper class that does auto-connection/picking best contest; clients who need this function can use it before creating a RESTContestSource.
Also fixed an issue with connecting to a root URL like /api (fixed child URLs) and made minor tweaks to messages.

Separate auto-connection and best contest picking to new API

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/ITeamMember.java
ContestModel/src/org/icpc/tools/contest/model/internal/TeamMember.java

Made the following changes:
- Make /api respond to requests in addition to /api/. Technically this isn't required by the spec, but I think it's better to do both.
- Add title to team member, the one property that's missing from person.
- Make /persons an alias to /team-members. This is a temporary hack that would be removed when team members is renamed.
The last change means that the /persons endpoint can be supported as per the spec *if read from disk* (or from a CCS that supports team-members and you don't need the new properties) and *if you don't care about the event-feed*. It's temporary, it's ugly, but it's a really cheap way to get a working /persons endpoint for now. FWIW I thought about implementing a full alias or putting both types on the feed, but that seemed like overkill.

Add title to /team-member and add temporary /persons endpoint

---

CDS/README.md
CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/service/BasicAuthFilter.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

Remove teamUser and hosts with teamId from CDS config. These overlap with accounts, and now that we have accounts we should use them instead. After this change, all team to account and individual team to host configuration is done via accounts as per the Contest API.
After this change:
- If you want to associate a team to IP/host or account, it must be done via an account in a contest. No more global config except for <host> mapping all team to host patterns.
- If you want a user to be able to log into the CDS, you configure them in (copy username and password to) users.xml.
- If you want auto-login, the user's password must be in accounts.json and there must be an IP or host in accounts.json or <host> in CDS config.
- User accounts are 'global', so if I can login to one contest and the …

Replace teamUser and host use with accounts, add /account

---

CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/js/contest.js

Added support for /account and /access to Javascript contest model, and changed the clarifications page so that the submit UI only shows up if the capability is available.

Hide clar submit when no capability

---

CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/ConfiguredContest.java

- Fix NPE when account type is null.
- Add some details to the public account to make it easier to debug.
- Make sure user accounts is empty if loading fails instead of null.
- Switch a few more account type strings to constants.

Account fixes

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/IContest.java
ContestModel/src/org/icpc/tools/contest/model/IContestObject.java
ContestModel/src/org/icpc/tools/contest/model/IPerson.java
ContestModel/src/org/icpc/tools/contest/model/ISubmission.java
ContestModel/src/org/icpc/tools/contest/model/TSVImporter.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/Account.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/ContestData.java
ContestModel/src/org/icpc/tools/contest/model/internal/MergingContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Person.java
ContestModel/src/org/icpc/tools/contest/model/internal/Submission.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamAwardPresentation.java

Renames team members to persons as per the spec change. Leaves the /team-members endpoint redirected to /persons so simple queries still work.
TSV importer gains ability to import accounts since I was already working on that class.

Team members -> Persons

---

BalloonUtility/README.md
BalloonUtility/src/org/icpc/tools/balloon/BalloonUtility.java
doc/ChangeLog.md

When two or more problems have matching UUIDs we should only print balloons for the first one solved. I've added a preference to disable this behaviour.
I also noticed that if a team submits multiple solutions to a problem we print multiple balloons. Likewise we should only give a balloon for the first solution to a problem (with no preference to change this).

Don't print balloons when problem UUIDs match

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

If a submission ever appeared in the feed before the team that submitted it, the submission would be lost, but that isn't allowed by the spec and seems pretty unlikely anyway.

Assume unknown teams were hidden

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/WebContent/WEB-INF/jsps/details.jsp
CDS/WebContent/WEB-INF/jsps/details/startStatus.html
CDS/WebContent/WEB-INF/jsps/layout/head.jsp
CDS/WebContent/js/types.js
CDS/src/org/icpc/tools/cds/AccessService.java
CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

Adds the ability to configure patch access for accounts to change individual contest objects, and a web UI to change the start-status when you have access.
On the server side, you can add CDS config to allow an account access to patch, e.g.:
<auth username="x" contestId="test" type="start-status" id="Sysops"/>
Individual attributes can be left out to specify "all", e.g. leave out contestId to allow patching on any contest. This is not documented until we get a little feedback and use at NAC.
/access is updated to include a "type/id" capability when you have access to patch something.
On the client side, start status items is now visible on the Details page. If the user has access (via the "start-status/<id>" capability) then the status is replaced by three buttons, just like the existing …

Per-account start-status control

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/WebContent/js/contest.js
CDS/WebContent/js/ui.js

Changes the CDS admin page to use the same formatting of contest time as the rest of the UI (including countdown presentations) so that the time always matches, especially at pauses. This was noticed by Tobi at SWERC where it looked like the admin and live view were 1s different.

Fix admin pause time

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/BalloonContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/StaffContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/TeamContest.java

The new contest filters weren't handling deletes correctly and causing NPEs. Deletions are special objects that can't be cast to a type.
The easy solution is just to pass through all delete events, since deleting objects that don't exist is ignored. One special case, the public contest needs to remove deleted problems from its pre-contest cache.

Handle deletes in new contest filters

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

If the provider has a filename, the tools attempt to use it locally. Otherwise, we are just using the property name, e.g. logo.png, logo2.png.
This switches it to append the image size if it exists, e.g. logo56x56.png, logo160x160.png.

Use image sizes in file reference names

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

SVG viewBox size was not being read in all cases, ending up in the cache with unknown size and causing re-downloads.
Also added small tweak so that new files with duplicate names use <name>WxH-2.<extension> (e.g. logo512x512-2.png) instead of <name>WxH2.<extension> (e.g. logo512x5122.png).

Parse SVG sizes in all paths

---

CDS/src/org/icpc/tools/cds/service/ContestWebService.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

At past contests we've had cases where we needed to look at the event feed/cache coming from the CCS, and to do that we had to log into the CDS and find the cache file. This change adds an admin-only endpoint <contest>/log so you can access the cache from anywhere. It isn't exposed through the UI for now, will try it out at NAC before deciding how to expose (likely on the admin page).

Access to event feed cache

---

PresCore/src/org/icpc/tools/client/core/BasicClient.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

Presentation client logs are too chatty, which both makes the logs hard to read and makes them hit the upload limit to send their logs back through the CDS. This removes the repeated standard messages by default.

Reduce pres client tracing

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
BalloonUtility/src/org/icpc/tools/balloon/BalloonUtility.java
BalloonUtility/src/org/icpc/tools/balloon/UPCa.java
ContestModel/src/org/icpc/tools/contest/model/FloorMap.java

Initial rewrite to switch the balloon printer from SWT to AWT printing. Printer configuration is still exposed in the UI via SWT but has no effect; printing just goes to default printer.
Background: we've had problems printing on Linux the last couple contests, especially where transforms (scaling) is used. Theory is that something has changed in Linux and SWT printing is not being maintained, may be better long term to use AWT graphics anyway.

WIP: Switch balloon util to AWT printing

---

PresContest/README.md
PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java
PresCore/src/org/icpc/tools/presentation/core/PresentationWindow.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

Remove the --fps command line arg and add a Ctrl-D to toggle debug mode instead, which shows fps, resolution, and presentation plan.
Why this change? Slightly simplifies the command line, provides more info, and (most importantly) can be turned on and off dynamically.
The presentation admin can already see all of this info, so I haven't added any ability to see the client debug state or control it from the admin. When an admin is being used I'm assuming we'll either continue to get the information there, or if we're directly at a machine just toggle debug mode on and off again. If that's not the case we could add this.

Remove --fps and add Ctrl-D

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDisplayPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScrollingScoreboardPresentation.java
PresCore/src/org/icpc/tools/presentation/core/Presentation.java
PresCore/src/org/icpc/tools/presentation/core/PresentationWindow.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Prior to this change you could add a listener to any presentation to register for key or mouse events. However, this was overly complicated and only one presentation (the team client display) actually added a listener - to itself. I'm simplifying this pattern to (only) allow presentations to easily listen to their own key & mouse events.
While I'm at it I added paging support to the scrolling scoreboard presentations. Using keys 1-9 and 0 (for 10) you can select which page of the scoreboard to scroll to. This allows a human user to control the scoreboard, e.g. for streaming while discussing the contest. This is just a teaser; we'll likely want to add more controls to the scoreboard (including a 'reset' option) or other presentations in the future.

Simplify keyboard/mouse binding

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestAPIHelper.java

At NAC I started a presentation client with a url like "https://cds", which - as I had literally just 'improved' a couple months ago - told me the URL was wrong and listed the contests it found under https://cds/api/contests. In my head it looked like auto-connection to the current contest wasn't working and I was confused.
Changing the wording from:
No contest found at the given URL, but I found these instead:
https://cds/api/contests/dress - Dress rehearsal starting at ...
https://cds/api/contests/finals - World finals starting at ...
To be a bit more clear and include the Contest API url:
URL invalid, but Contest API found at: https://cds/api/contests
https://cds/api/contests/dress - Dress rehearsal starting at ...
https://cds/api/contests/finals - World finals starting at ...

Improve wording when Contest API found

---

ContestModel/src/org/icpc/tools/contest/model/feed/CDSUtil.java
ContestModel/src/org/icpc/tools/contest/model/internal/Ranking.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/Admin.java

A few minor fixes that I found either at or testing for NAC:
- NPE when ranking if teams are tied and have no name. Unlikely in any real contest, but I hit it in testing.
- Presentation admin fails when there are no args, should output help.
- Older builds of the tools had 'v' in the version string, causes an error if they are on the CDS and we don't strip it from the version.

Assorted minor fixes

---

PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/CommentaryPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/MessagePresentation.java

Upgraded the text helper to support "contest object" items and multiple lines, and put it in use for the commentary and message presentations. This means both presentations can now support the proposed {type:id} format, so far including teams, organizations, problems, and persons. The drawing of each item has been improved (e.g. teams and orgs include logos, persons include photos, problem label is prettier), as well as multi-line layout, improved string splitting (if there's no \n), and support for many layouts (alignment, indentation, etc). Any of these things could probably be useful elsewhere too, we'll figure that out later.
Messages or commentary can now be things like "Has anyone seen {persons:bill_poucher}?\nHe was last seen near {teams:43}, who were working on {problems:D}".

Commentary and message upgrade

---

CDS/src/org/icpc/tools/cds/presentations/WebSocketConfig.java
ContestModel/src/org/icpc/tools/contest/model/feed/CDSUtil.java

Two minor fixes:
- When checking the CDS for updates, output the version string if it's invalid
- Avoid NPE in web socket if the user isn't logged in

Minor fixes

---

CDS/src/org/icpc/tools/cds/AccessService.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/ContestObject.java
ContestModel/src/org/icpc/tools/contest/model/internal/SimpleSet.java

Finished /api implementation and added endpoints to /access. With this change the CDS is now compliant with the current Contest API spec and will give correct results based on the user's role, with one major caveat: endpoints are calculated by building a list of objects and properties as they are added to the contest for each role. This means that /access is correct by the end of a contest, but during a contest endpoints are missing if we haven't seen them yet (e.g. problems or submissions before the start of a contest) or individual properties might be missing if something hasn't happened yet (e.g. clarifications won't have 'to_team_id' if nobody has replied directly to a team yet).
This is still worth releasing since it as good as we can do until there are CCSs that provide an /access …

Contest API provider and endpoints

---

ContestModel/src/org/icpc/tools/contest/model/feed/NDJSONFeedParser.java

@deboer-tim the new format broke as found out by @meisterT on the CDS we set up for the Dhaka test. After reproducing it locally it seems to be this issue.

Fix event feed parsing for new format for contest type.

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java

Also change hiding of runs during freeze to be based on submission time.
And add null check for judgement
@deboer-tim Lidia from Live asked why she got a run without a judgemenet and it turns it she never should've gotten the run because the submission of that judgement was outside of contest time. So I added that check to the filter.
Turned out we didn't return any runs that happened during the freeze, while we should return them if the submission itself was before the freeze, so I also fixed that. Finally there was a possible null pointer exception that is now fixed.

Hide runs of submissions outside of the contest for analysts.

---

CDS/WebContent/WEB-INF/jsps/errorPage.jsp
README.md

There are more mentions of the site at baylor, will that server be recovered?

CLICS Specs are currently hosted at github.io

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
CDS/src/org/icpc/tools/cds/video/VideoAggregator.java
CDS/src/org/icpc/tools/cds/video/VideoHandler.java
CDS/src/org/icpc/tools/cds/video/VideoServlet.java
CDS/src/org/icpc/tools/cds/video/VideoStream.java
CDS/src/org/icpc/tools/cds/video/containers/FLVHandler.java
CDS/src/org/icpc/tools/cds/video/containers/MPEGTSHandler.java
CDS/src/org/icpc/tools/cds/video/containers/OggHandler.java

Added Ogg support to CDS:
- Fixed an issue where a different object was being passed to writeHeader() and createReader(), which meant that headers weren't sent for any format.
- Updated video handler, FLV, and MPEG handlers so that we can get the mime type, file extension, and validate a stream. The latter is unused for now, but would allow us to either validate that the CDS/incoming video stream is configured properly, or potentially even auto-detect and support all three formats at once.
- Updated places where the mime type or file extension was hard-coded (playback contest, video servlet).
- Added Ogg handler. Basic for now; can add capability to renumber packets as necessary.
- For now, only one format is active for all streams. MPEG remains the default, Ogg is triggered by setting …

Ogg support

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/service/ProjectionScoreboardService.java
ContestModel/src/org/icpc/tools/contest/model/Scoreboard.java

Remove support for after_event_id, which was removed in the 2022_07 spec and is no longer required. Just removes dead code and makes things a little shorter and easier to read.

Remove after event id

---

CDS/WebContent/WEB-INF/web.xml

Changes I made in the last year to simplify auth have inadvertently moved video streams to https. We have no reason to believe this would be a problem... but also no proof that it isn't a lot of overhead like the last time we tried this >5 years ago, nor any good way to test before Dhaka. As per decision on sysops call I am reverting streams, hopefully not at the expense of anything else.

Revert streams to http

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java

As discussed on the last sysops call, awards should not be publicly visible in general. The one exception is FTS awards before the freeze.
This change fixes it with one obvious exception: if a submission happens before the freeze and the award is given after the freeze, it won't be publicly accessible. I don't think this is worth fixing for now, and can be deferred until we update the access policy:
- it's difficult and potentially ugly (you'd need to find the problem based on award id, then look for team's submissions for that problem, and if any submission was before the freeze and solved...)
- we doubt anyone is using these awards anyway

Reduce award access

---

CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/IOrganization.java
ContestModel/src/org/icpc/tools/contest/model/TSVImporter.java
ContestModel/src/org/icpc/tools/contest/model/internal/Organization.java
ContestModel/src/org/icpc/tools/contest/model/internal/Person.java
ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
ContestUtil/src/org/icpc/tools/contest/util/cms/GoogleMapsGeocoder.java
ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java

Downloaded the latest config from CMS, which required several fixes. Since these touched files where I had already added minor support or fixed bugs while testing it I've grouped them together:
- Fixes to both TSVImporter classes b/c the CMS column reordering is fixed.
- Added new "twitter_account" property to organization and started reading it from institutions2.tsv (it's now a new column).
- Renamed getHashtag() to getTwitterHashtag() so the two Twitter properties are clear and match.
- Fixed coach view org logo so it's always over top of text.
- Fix to geocoder, b/c Nicky didn't test his code on a plane with no internet :) .
- Added support for reading person photos from CMS, cleaning them up, and putting them in the right contest package folders.
- Fixed bug in person where copies …

Config updates

---

ContestModel/src/org/icpc/tools/contest/model/internal/Person.java
ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java

- Fix person to output team_ids property.
- Image generation fix for tile (160x160px) images.
- Sort persons.json by id (sorting by team was causing more diffs).
- TSV importer fix for persons with multiple teams.

CMS config generation fixes

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/MessagePresentation.java

The contest banner for this year is not as wide as previous years, so it takes up too much of the messages presentation. Setting a lower limit on the vertical height so that it doesn't scale as big.

Limit height of message banner

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

Changes to add /access support broke removing objects, need to make sure it checks for null properties

Null check when adding known properties

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonUtility.java
CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestAPIHelper.java

REST source hasn't touched the CDS yet so the flag isn't set. I don't like using ContestAPIHelper directly, but that's the only thing that's pinging the CDS.

Fix auto-update for coach view and balloon util

---

CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

Avoid adding null entries to file references list if the file metadata can't be found. Try twice before doing so. This is a bit of a hack - we know there's a file on disk, but we can't get any details about it. Trying twice will tell us if it's a temporary/timing problem or not, and better to never add null file ref (i.e. miss telling clients about one reaction vs crashing). Also two fixes to reaction video recorder:
- Fix potential problem with file extension length if we use another video container.
- Don't delete 0-byte downloads. This will be more annoying to clients, but avoids adding the file on another CDS and then deleting the underlying file.

Avoid downstream effect of "Null file ref"

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonUtility.java

Skip using swing thread when calling print, since print() method does it internally. Second auto-print should check if the balloon is already printed

Avoid printing twice

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

The jpeg mime type was incorrect. This caused additional downloads whenever the CCS served files via the Contest API, b/c the image size might be identical but the different mime type triggered the CDS to download.

Fix mime type

---

CDS/src/org/icpc/tools/cds/CDSConfig.java

If the cdsConfig.xml was broken at startup, things were left in a null state and the welcome page wouldn't even load. This Also added a trace for removing contests.

Always initialize contest array

---

ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java

I realized too late that CMS changed columns in persons.tab since the last finals. Hopefully we won't need to use this import again, but fixed the problem just in case, and made it more resilient by searching for the column name.

React to CMS changes

---

ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

The special group award names that had to be there for previous WF now have to not be there. Removing the special award handling for certain group names.

Default group award names

---

ContestModel/src/org/icpc/tools/contest/model/internal/Group.java

Groups don't require an external id, removing invalid validation.

Groups don't need external id

---

CDS/WebContent/WEB-INF/web.xml
CDS/src/org/icpc/tools/cds/CDSAuth.java
CDS/src/org/icpc/tools/cds/util/HttpHelper.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
CDS/src/org/icpc/tools/cds/video/VideoServlet.java
CDS/src/org/icpc/tools/cds/video/VideoStream.java
CDS/src/org/icpc/tools/cds/video/VideoStreamListener.java
ContestModel/src/org/icpc/tools/contest/model/feed/JSONEncoder.java

We initially tried HTTPS >10 years ago, and removed it for video when we hit a performance problem that was triggered when live accidentally did a DoS attack. Since then there has been a hesitation to try it again due to lack of a systems test and worry that some clients (e.g. VLC at the time) couldn't handle HTTPS well.
All clients that I've tried now support HTTPS (it's pretty much standard now) and David did some performance tests in Dhaka which confirmed that the overhead for HTTPS is negligible. This change:
- Moves all CDS content to HTTPS (was just missing video streams before).
- Removes the block on HTTPS in video servlet.
- Renames 'trusted' to 'analyst' to match the account type.
- Moved hardcoded 'http' to be part of '<host>' so that the transport, host, and port are all …

Move video streams to HTTPS

---

CDS/src/org/icpc/tools/cds/presentations/PresentationWebSocket.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/ClientsControl.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/View.java
PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/PresentationClient.java
PresContest/src/org/icpc/tools/presentation/contest/internal/ScalingTestClient.java
PresCore/src/org/icpc/tools/client/core/BasicClient.java

Coach view was using the same UID (hash of user name) for all clients trying to connect to the CDS. This resulted in a lot of repeated "Disconnecting client with existing uid" messages in the CDS log, and eventually even a CPU spike due to garbage collection threads (no real clue why, but stopping coach view fixed it).
Switched to always use the hashcode of "username + network address" for all clients and improved the error message a little. While using the admin to test I noticed a case where thumbnail images aren't disposed of properly, fixed this as well.

Improve UIDs for CDS clients

---

ContestModel/src/org/icpc/tools/contest/model/util/ContestComparator.java

The contest comparison code didn't handle arrays, so they'd always be different and the output comparing the two was useless. This change compares the elements of each array to see if the elements match (regardless of order) and improves the output to look like this: "Different silver-medal: property team_ids ([5,6] vs [5,6,7,8])"

Improve comparison of arrays

---

ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

I plan to review how multiple CDSs on a shared filesystem works, but short term it should be deleting temp files if another CDS was faster at downloading files than the current one.

Delete temp files if another CDS was faster

---

ContestModel/src/org/icpc/tools/contest/model/feed/ContestAPIHelper.java

The balloon printer failed to download and install updates from the CDS, with an xml parsing error in the logs. I couldn't recreate or figure out why until later: someone had put "http://cds" in the URL instead of https. Even though the contest detection/verification code was following redirects (to something like https://cds/api/contests/dress) the code to look for updates is just going to a relative url based on the original (http) url.
Instead of making the update code follow redirects, I have changed the contest detection to return the final URL where it found a contest. Aside from indirectly fixing the update problem (because the update code won't ever need to follow a redirect) this has the added benefit that clients will always connect to the real url and have one less redirect …

Redirect clients to the final contest url

---

CDS/.classpath

The CDS includes 2 new jars but I forgot to commit the .classpath file that adds them to the build path in Eclipse

Add missing jars to CDS classpath

---

ContestModel/src/org/icpc/tools/contest/model/feed/JSONParser.java

Fixes parsing of empty objects like '"location":{}' (and will validate other odd problems better).

Parsing fix for empty objects

---

.github/workflows/ci.yml
README.md
build/builder.Dockerfile
build/cds/Docker/Dockerfile
build/readme.build.txt
build/website.Dockerfile
website/content/cds.md

This should be all to replace Docker Hub by GitHub Container Registry, now that Docker Hub wants money.

Use Github Container Registry for Docker images.

---

ContestModel/src/org/icpc/tools/contest/model/internal/Language.java

The latest spec was changed to have a consistent underscore, this will read either and output the new format.

Fix language version command

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
BalloonUtility/src/org/icpc/tools/balloon/SummaryPrint.java
BalloonUtility/src/org/icpc/tools/balloon/TeamSummaryPrint.java
CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/WEB-INF/jsps/commentary.jsp
CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
CDS/WebContent/WEB-INF/jsps/registration.jsp
CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
CDS/WebContent/WEB-INF/jsps/submissions.jsp
CDS/WebContent/WEB-INF/jsps/teamSummary.jsp
CDS/WebContent/WEB-INF/jsps/video.jsp
CDS/WebContent/focusScoreboard.jsp
CDS/WebContent/js/types.js
CDS/WebContent/js/ui.js
CDS/WebContent/solvedSubmissionList.jsp
CDS/WebContent/submissionList.jsp
CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
ContestModel/src/org/icpc/tools/contest/model/IProblem.java
ContestModel/src/org/icpc/tools/contest/model/ITeam.java
ContestModel/src/org/icpc/tools/contest/model/internal/Team.java
ContestUtil/src/org/icpc/tools/contest/util/EventFeedUtil.java
ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/SingleTeamPresentation.java
Resolver/src/org/icpc/tools/resolver/awards/AbstractAwardDialog.java
Resolver/src/org/icpc/tools/resolver/awards/AwardUI.java

We're adding team labels to the Contest API, so we need to match this throughout the tools.
This PR covers:
- The actual API change.
- Default label to the id if it isn't present (this is a bit of a hack done when the name is set - couldn't think of a cleaner way). This ensures that clients can always rely on the label and it is there even if the CCS/contest package doesn't have one.
- Impact to all downstream clients: balloon printer, coach view, presentations, award util, and CDS web views.
Could I have missed something? Sure. I did a pretty thorough search which turned up all the impacts that I could think of, but until we test at NAC we won't know for sure. For now I switched all 'user output/messages' to labels, but left the few internal log messages as id because that's what you'll …

Team label support

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/CountdownPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/SitesStatusCountdownPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/StatusCountdownPresentation.java

- Remove banner vertical clock adjustment for status countdown (issue #770).
- Change "Status: Go" when there are status sliders not ready (issue #749).
- Increase the maximum time speed (we had a few cases where the clock was reset a large distance, just reduces the time to reset).
- Standard formatting for SitesStatus.

Clock improvements

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

- Support default team and person photo. Drop a photo in 'default-id' folder for either and it'll be used whenever there is no photo (issue #534).
- Correctly support .jpeg file extension mime-type.
- Add support for downloading backup, key log, and tool data from contest source (CCS). Not there today, but keeps things consistent.

Resource loading updates

---

BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java

-Reduce font sizes just a little.
-Make 'no existing' message shorter.
-Fade unsolved balloon label and colour.
-Rotate balloon colour names so they don't overlap.

Improve balloon printout

---

ContestModel/src/org/icpc/tools/contest/model/IContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Info.java

Although it's ugly, IMHO the only way to implement #808 (contest banner in resolver and presentations) 'properly' is to set a color on the contest object, the same way that problems have colors (in fact, this implementation is copied from there).
In the contest configuration we add a file like `extend-color/contests.json` with contents like:
`{"id":"sharm","rgb":"FF0000"}`
Now all clients see the correct color to use in the contest endpoint or feed. Presentations and resolver can use it for the contest-specific banner. No command line args required for color; clients that load two contests can see a value per-contest. Live can pick up the correct color too; or if they choose to set it differently, at least it is clear what we are using and when it doesn't match.

Color value for contests

---

CDS/WebContent/WEB-INF/jsps/admin.jsp
CDS/WebContent/WEB-INF/jsps/countdown-control.jsp
CDS/WebContent/WEB-INF/jsps/countdown.jsp
CDS/WebContent/WEB-INF/jsps/layout/head.jsp
CDS/src/org/icpc/tools/cds/service/CountdownServlet.java

Fixes #814
This also fixes a bug with the lock button, where you needed to press it twice to do the initial lock.
Basically this extracts the countdown logic to it's own JSP and it now has two modes:
* The old behaviour where it would manage one contest. Nothing changed here except some HTML ID's and I have moved the status label to after the countdown, to be consistent with the new mode.
* The new behaviour where it can manage multiple contests. You can toggle what contests to manage and by default it manages all non-started contests, since that is probably what you want if you use this mode.
The new mode basically just loops over all contests and does the old logic for most buttons and javascript.
I also made it that if you performed an action that it will clear the info of the contest, …

Add ability to start multiple contests at the same time.

---

PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/SnakePresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDisplayPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/WavePresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/TeamUtil.java

Update TeamUtil to support team labels in addition to ids. Uppercase the environment var and system properties we look for, and use _ instead of - to match the spec better.

Update team machine identification heuristics

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/IFilteredContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/SpectatorContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/TeamContest.java

Make a few minor improvements to simplify/centralize access control (e.g. file references also use filtered contests now; analysts extend spectators since they're closer to that now), and implement changes for the approved contest information access policy: https://docs.google.com/document/d/1Jgqaxsu_nFb94MkIcBsSXFIKCasdkuxQsxGoKksRQEI

Contest access control policy

---

ContestModel/src/org/icpc/tools/contest/model/internal/Account.java

Fix for issue #810 - account name wasn't being JSON encoded (no idea why).

Encode account name

---

ContestModel/src/org/icpc/tools/contest/model/IPause.java
ContestModel/src/org/icpc/tools/contest/model/internal/Pause.java

We're not using contest pauses (long history omitted), but I noticed the CDS implementation is still expecting/outputting integers in JSON instead of timestamps like everything else in the spec. Switching it over just to clean this up.

Pause timestamps

---

ContestModel/src/org/icpc/tools/contest/model/IResult.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Info.java
ContestModel/src/org/icpc/tools/contest/model/internal/Result.java
ContestUtil/src/org/icpc/tools/contest/util/EventFeedUtil.java

The previous change for long penalty time was incomplete and causes the penalty to be 0 on the scoreboard. This fixes that problem and follows references to make sure that Result is also fully switched over to long ms time values. Standings and all other classes are left with penalty as an integer (minute) value.

Fix penalty time

---

CDS/src/org/icpc/tools/cds/video/VideoAggregator.java
CDS/src/org/icpc/tools/cds/video/VideoHandler.java
CDS/src/org/icpc/tools/cds/video/VideoServingHandler.java
CDS/src/org/icpc/tools/cds/video/VideoServlet.java
CDS/src/org/icpc/tools/cds/video/VideoStream.java
CDS/src/org/icpc/tools/cds/video/VideoStreamHandler.java
CDS/src/org/icpc/tools/cds/video/containers/FLVHandler.java
CDS/src/org/icpc/tools/cds/video/containers/FLVReader.java
CDS/src/org/icpc/tools/cds/video/containers/HLSFileCache.java
CDS/src/org/icpc/tools/cds/video/containers/HLSHandler.java
CDS/src/org/icpc/tools/cds/video/containers/HLSParser.java
CDS/src/org/icpc/tools/cds/video/containers/MPEGTSHandler.java
CDS/src/org/icpc/tools/cds/video/containers/OggHandler.java

This is the initial batch of changes to support HLS. It makes the structural/URL-facing changes required to support file-serving video formats (vs streaming), and sets the default video format to HLS (even though it's not really working yet!).
There is a *lot* of change in order to support HLS so I need to start pushing a branch, but there are numerous limitations (and likely some I still don't know about) listed in issue #812 and at the top of the HLSHandler. The current code works for one stream at a time, and hasn't been tested except through Safari.

Initial HLS support

---

Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

We may not use this in Sharm anyway, but I had already written the code and I think it's useful in other cases. The resolver could already load multiple contests (command line argument url1&url2&url3), and this adds support for easily swapping between them at any point by pressing 's'.
For example, if you want to resolve a contest for division 1 and then a second contest for division 2, you don't need to finish one, exit, change the command-line/batch file, and launch the other - you can just resolve one and click 's' to start the next one. Or if you're in Sharm, you could swap back and forth ad nauseam.
This only works for presenters/standalone at the moment, no signal is sent to clients. It may also halve the frame rate after switching (?) because I didn't confirm it totally backgrounds …

Resolver multi-contest switching

---

Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Implemented a property to let clients know when the resolver presenter switches active UIs (contests). This is really just bringing back one global property so the code is almost copy/paste of some of the previous code.
Using this I am able to bring up a resolver presenter and client both pointing to two contests, and you can resolve and swap both whenever you want. Alternately, you could still have two clients each pointing to a different contest; the single presenter can still swap between them and resolve. I used a string contest id property so technically you could have one presenter controlling multiple clients each of which is showing different contests... although that'd be confusing.
I've confirmed that swapping UIs means that the unswapped presentations are still running in the …

Multi-client resolver swap

---

ContestModel/src/org/icpc/tools/contest/model/internal/Language.java
ContestModel/src/org/icpc/tools/contest/model/internal/Person.java

These changes should allow the CDS to use the 2023-06 version of the spec, but accept input and provide output that's compatible with the 2022-07 version. Specifically:
- person team_id input will output team_id and team_ids with a single team. team_ids input of more than one team will still output the first team_id and all team_ids.
- language will accept version-command or version_command, and output both.

Spec inter-compatibility fixes

---

ContestModel/src/org/icpc/tools/contest/model/internal/Group.java
ContestModel/src/org/icpc/tools/contest/model/internal/Info.java
ContestModel/src/org/icpc/tools/contest/model/internal/Location.java
ContestModel/src/org/icpc/tools/contest/model/internal/Organization.java

The CMS outputs empty locations (location:{}) for orgs that don't have one set. Although we're trying to fill these in, it's better if the CDS doesn't have a location element for these cases, or where the location wasn't readable.

Empty locations

---

CDS/src/org/icpc/tools/cds/video/VideoServlet.java
CDS/src/org/icpc/tools/cds/video/containers/HLSFileCache.java
CDS/src/org/icpc/tools/cds/video/containers/HLSHandler.java
CDS/src/org/icpc/tools/cds/video/containers/HLSParser.java

Made a few changes after testing against Patrick's cameras:
- Indefinite HLS index caching was breaking the video - only cache for 500ms (unfortunately this means the index cache rarely gets hit).
- The cache size for very low bandwidth feed for 20s was 2.9Mb. Drop the cache to 10s, and from the time of storing instead of last access. This drops it to ~1.4Mb/stream (still low bandwidth).
- Redid some of the logging and replaced e.printStackTrace()s. We still need to reduce console output per stream - but after caching is fixed.

HLS improvements

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java

Generate multiple icons, so we can have 56x56 and 64x64.

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java

Fixes #870.
Although this was not the highest prio, it WAS something I could fix easily.
I decided to **not** use a `ICPC_FINALS` flag or anything, but use a generic one. It works both with a system property and an env var, just like `TEAM_ID` does.
We should make sure the env var or system property is set at the finals, we should be able to do that with Ansible, I can take a look at that after this is merged.

Add env var / system property to hide country info.

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

The contest's initial info and state were being set in the initializer, but not written into the contest data in the constructor. With a default/empty state the endpoint correctly returns "{}".
Fixes #860.

Return valid (empty) contest state if it has never been set

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/TeamContest.java

Removes the clarification reply_to_id if the receiver can't see the original clarification.
Mostly for paranoia and consistentcy it's done for teams as well.
Fixes #871.

Hide clarification reply to id if the account can't see it

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

Due to the refactoring of the resolver code, client is loaded later and would sometimes be null at line 629, which meant non-presenter clients would have keyboard control. It wouldn't send events in, but it could get things out of sync until the presenter does something. This change makes it clear that isPresenter is the only indicator of control.
Fixed one ERROR to INFO.

Resolver clients shouldn't have control

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/BalloonContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java

Moved thawing out to its own method, and call add() to make sure objects are still filtered if necessary. Required a couple new checks to let objects through if the contest was frozen but is now thawed.
The original issue mentioned a few object filtering methods:
- Judgement - should now be sent filtered.
- Person - not filtered during the freeze, irrelevant.
- Problem - not filtered during the freeze, irrelevant.
- Submission - some properties are filtered, but I'm not going to get fancy in this PR and try to update them later. It actually should be as simple as adding them to 'freeze', but that can be done later.
Fixes #859.

Correctly filter objects sent on thaw

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

Return 404 if client requests an object id that doesn't exist.
Fixes #862.

Return 404 for bad id

---

PresContest/src/org/icpc/tools/presentation/contest/internal/PresentationClient.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/BrandingPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java

Allows a 'branding presentation' to be applied to presentation clients via an ICPC_BRANDING_PRESENTATION in a system property or environment variable. This presentation could do anything, but the supplied default one adds a banner across the top of the screen with the contest name and color.
For now this is per-client via the system property/env var to see how it works. If it does, we can expose through a command line property or admin control, or make different branding presentations.
Fixes #808.
Replaces #813.

Presentation contest branding (banner)

---

PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

When the window is not visible, slow down the frame rate to avoid using CPU.

Reduce fps when not visible

---

CoachView/src/org/icpc/tools/coachview/CoachView.java

During testing I found a case where reactions == null, just catching this case to avoid error.

Coach view: avoid error when reactions is null

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java

Just allows you to filter properties by `"<null>"` to find cases where a property is unset.

Allow contest object filtering by null

---

PresCore/src/org/icpc/tools/client/core/BasicClient.java

We ran into a case at some contest where the network name wasn't unique enough to differentiate between clients. This just adds the hostname into the uid generation for more uniqueness.
Also adds a null check for the clients list.

Add hostname to client UID generation

---

ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

When we fixed an issue with default contest state I thought I'd be clever and also fix the default contest info. This was a bad idea, because a default contest info has no id or name, since we don't know that yet. And having a contest info with the wrong id, etc. in the history causes worse problem, like not merging correctly when there is new data, causing the / endpoint to return two contests, scoreboards to fail, ...
There was no need to make this part of the change, so let's remove it. :)

Remove default contest info

---

ContestModel/src/org/icpc/tools/contest/model/internal/YamlParser.java

There's a new (proposed) standard for specifying problem time limits in problem.yaml. systest0 used this instead of the historic .timelimit file, which caused some problems to have no time limit on the CDS until we connected to the CCS, which caused problems for analytics.
This just adds support for reading the time limit from the yaml.

Read problem time limit from problem.yaml

---

CDS/src/org/icpc/tools/cds/service/ResolverService.java
ContestModel/src/org/icpc/tools/contest/model/IResolveInfo.java
ContestModel/src/org/icpc/tools/contest/model/internal/ResolveInfo.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionControl.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScrollingScoreboardPresentation.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Adds [ { and } ] keys to control the speed of scrolling in the resolver, for both the main scoreboard and team award list.
In the future we may want to:
- combine this with +/-, i.e. you use the same keys but it only affects the screen you're on.
- separate the main scoreboard scrolling from team list award scrolling.
but this adds the basic support that allows it to work, which we can expand on later.
Fixes #108.

Resolver scrolling speed control

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/BrandingPresentation.java
PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

Presentations 'inside' a branding presentation were not receiving their property changes, e.g. you couldn't set the text on a message presentation. This is because each property is passed to a specific presentation, and since e.g. branding pres != message pres, it wouldn't be told about the property change in order to pass it on.
This makes the branding presentation special and told about all property changes, and it in turn decides if the presentation should be
Ok, I know this is getting a little ugly, but still better to do the minimal change for supporting 'branding' presentations until we know how we would want to use them long term.

Fix properties when using a branding presentation

---

Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Unfortunately the branding code needs to be added to the resolver UI in addition to the presentations. I already have better ideas of how to do this in the future, but for now this is an easy (and now tested) way to load the contest 'branding'.

Resolver branding

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java

The contest info object is now in the default configuration so that we can support extended properties like the rgb value. However, that means when a CCS doesn't send a contest time (e.g. during a pause), the CDS will set the default (original) value back. This puts in a temporary fix to never set the default value for contest start time. Later we should revisit; using the contest /access endpoint might be a better solution.

Fix issue resetting contest start

---

ContestModel/src/org/icpc/tools/contest/model/internal/account/SpectatorContest.java

Spectator is doing its own logic for submissions, but it just calls the parent class - which does the identical thing and calls filter. We can just skip this logic and let the parent do its thing.

Unnecessary filtering in spectator account type

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/BalloonMapPresentation.java

When a team is far away from the contest site the arc a balloon takes to travel there is noticeably a set of line segments in an arc approximating a curve. We could get fancy and have a variable number of segments depending on the distance or switch to an actual curve... but just increasing the number of segments should be fine.

Increase segments in balloon map pres

---

ContestModel/src/org/icpc/tools/contest/model/feed/HTTPSSecurity.java

This broke PUTting to the CDS. Strangely it didn't break for GET's, but this doesn't hurt in general.

Do not check if certificate has correct subjact altnerative name.

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java

If a contest is configured in a folder where the contest id doesn't match the folder name, and there is no CCS configured, and the contest id isn't set in cdsConfig.xml, we should be picking up the default contest id from the contest.yaml, not the folder name.
Adding support for this only for contest.yaml, not contest.json for now. We could wait until the contest is loaded and let the disk contest source load the id, but this delays too much, e.g. clients might be able to see the endpoints or contest exist in the web pages first.

Default contest id from yaml

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/IFilteredContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/SpectatorContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/TeamContest.java

Change allowFileReference() to more generic canAccessProperty() and allowProperty() functions. canAccessProperty() returns true if a type property is supported for some object & time (i.e. could be basis for access endpoint in future), while the second asks 'can I access this property on this specific object now?'.
Filtering for team and submissions use these methods, building from 'public' role to spectators and analysts.

Simplify access filtering

---

Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Instead of each resolver using it's own window and trying to swap the
visibility, just open one window and swap whether the resolver UI is
active by (re)setting the current presentation and enabling/disabling
keys and mouse.
Allows a seamless and faster transition between contests without any
flashing.

Use single window for multi-contest resolver

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

We used to use the same type (`resolver`) for all connections, which means the CDS keeps kicking us out, since there can be only one client per uid. Adding the connection index seems to fix this.

Make uid for multi resolver unique.

---

PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java

- Allow the TextHelper to draw text with outlines, and use it in the photo presentation for team names.
- Remove SelectType code, since it wasn't being used.
- Reduce font size.
- Add gap at the top.
- Center the last row (when necessary).

Improvements to team photo list presentation

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

- When using a template/award util, the solution award assigns a parameter with the number of solved problems. This is used to make sure the award does not appear until that number of problems has been solved.
- Team list and photo awards can use a parameter "after" (manually assigned) to indicate that they do not want to appear until after individual awards.

Added resolution options for solution, list awards

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java

Allows clients to provide a name when creating a REST connector. Having a unique name means that the cache will be created in a different file, avoiding two users loading the same cache. If no name is provided, the user name is used since most users have different access roles.
This allows allows moving the CDS's use of different caches out of the REST connector, since it shouldn't really be in there.

Use different names for event feed cache

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

Use the same method as solution awards to decide when to show the honorable mention award: let the award specify how many problems the top team has solved. This will stay on the judge queue until the scoreboard has judged enough runs.

Stay in judge queue until team above HM has solved at least 1 more

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java

Remove outline from team name (since we use bg now). Center the team name vertically.
Eclipse changes to make formatter and checker happy.

Minor improvements to team photo list

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java

Fixes two minor issues I noticed:
- When cleaning up, flushes wrong images (and can cause exceptions).
- Spacer between logo and team name should be smaller, and proportional.

Team photo fixes

---

ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
ContestModel/src/org/icpc/tools/contest/model/feed/ContestWriter.java

Adds a new 'force' option to the contest writer. If force is not true then empty lists or singletons will not be written as new files.

Contest write force / singletons

---

ContestModel/src/org/icpc/tools/contest/model/internal/Info.java

Without this the resolver assumed scoring as the default, meaning nothing showed up.

Make pass/fail the default scoring algorithm.

---

doc/ChangeLog.md
version.properties
website/content/_index.md

Move builds to version 2.6, update changelog, and remove warning from website.

2.5 release updates

---

PresContest/src/org/icpc/tools/presentation/contest/internal/ICPCColors.java

Change the PENDING_COLOR to a shade of blue instead of yellow in order to improve accessibility for colorblind folks. The current shade of yellow is very hard to distinguish from the green SOLVED_COLOR.
This change is discussed in Issue #978. This color choice is Option 2 in that discussion. Screenshots can be found there. If you have further comments on the color choice, please continue the discussion in Issue #978

Change PENDING_COLOR to (66,114,245)

---

ContestModel/src/org/icpc/tools/contest/model/IAward.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
ContestModel/src/org/icpc/tools/contest/model/util/messages.properties
ContestModel/src/org/icpc/tools/contest/model/util/messages_es.properties
Resolver/src/org/icpc/tools/resolver/awards/TemplateAwardDialog.java

Update the old honorable mention award template to support both percentiles and 'number of solved problems compared to the lowest medalist'.
Fixes #994.
Add some special cases:
* The highest honors should not be displayed as a list or anything
* Any list that overlaps or is just below the medalists, should be displayed before resolving medalists

Implement new honors awards

---

BalloonUtility/scripts/balloon.sh
CoachView/scripts/coachView.sh
ContestModel/doc.sh
ContestUtil/scripts/contestUtil.sh
ContestUtil/scripts/eventFeed.sh
ContestUtil/scripts/eventFeedSplitter.sh
ContestUtil/scripts/scoreboardUtil.sh
PresAdmin/scripts/presAdmin.sh
PresContest/scripts/client.sh
PresContest/scripts/standalone.sh
ProblemSet/scripts/problemSet.sh
Resolver/scripts/awards.sh
Resolver/scripts/resolver.sh

As described in #1002, the `#!/usr/bin/env bash` shebang is more generic and looks for bash in `PATH`, instead of assuming `/bin/bash` is present. This makes it so that the scripts work on, NixOS, OpenBSD, ...

Update shebangs to more generic version

---

PresCore/src/org/icpc/tools/client/core/BasicClient.java
Resolver/src/org/icpc/tools/resolver/Resolver.java
Resolver/src/org/icpc/tools/resolver/ResolverUI.java

Gets rid of --presenter and --client options. When you connect to a CDS, it tests if you have presAdmin access. If you do, you are presenter. If not, it says you are a regular client.
When not connecting to a CDS, you're always presenter.
Fixes #959.

Simplify presenter vs client

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/OrgLogoSlidePresentation.java

If you have less than 4 teams in a contest (or this is the first pres and contest data hasn't loaded yet) you get a divide by zero because there are no teams in the row.

Avoid divide by zero when <4 teams in org logo pres

---

CDS/src/org/icpc/tools/cds/service/CountdownServlet.java

Eclipse linting now prefers different ordering, and svUID in servlets.

Countdown linting and svUID

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java

I turned off generating team desktop images at some point, we should do that now.

Re-enable team desktop image generation

---

ContestModel/src/org/icpc/tools/contest/model/internal/Person.java

We should validate coach's teams the same as contestants. Both should validate all teams, not just the first.

Improve person team validation

---

PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/TeamUtil.java

Add trace messages whenever we look up a team id (which should only happen once, for team displays), so that we can determine what happened if it can't determine a team id.

Tracing for team id

---

PresAdmin/src/org/icpc/tools/presentation/admin/internal/Admin.java

Since the presentation admin is 'global' and can control multiple contests /presentations at once, the correct path to access the CDS is the CDS root, e.g. something like http://cds/ or https://10.3.3.207:8443. People frequently include the contest api in the url though, e.g. https://cds/api/contests.
Although giving an error is 'correct', we've had a few requests to just make it work. So instead of an error, this output a warning and tries the url without the path.

Autocorrect presentation admin CDS root with path

---

PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java

The helper method `paintRecentBackground()` was re-checking `ContestUtil.isRecent()`, but the `contest` used might be updated concurrently, and in that case a white background was drawn with a `null` `Color`, causing white flashing. The helper function is only used to draw recent updates, so this renames the function to `paintRecentResultBackground`, and removes the extra check.
white flashing:

Always draw recent background in helper function

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

Fixes #958
doneUpdating() means the data is public, but sometimes you still want to test with a feed with this data, which you can't do anymore currently. Changing this into a warning makes it so people still know but you CAN test.

Change presenter done updating logic to warning

---

CDS/src/org/icpc/tools/cds/video/VideoStream.java
CDS/src/org/icpc/tools/cds/video/VideoStreamListener.java

There is no analyst role anymore; rename to staff (which matches how it is set).

Rename analyst to staff

---

PresContest/src/org/icpc/tools/presentation/contest/internal/tile/AbstractTileScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java

Make the adjustment for all tile scoreboards,
do not adjust if number of rows is explicitly set,
reset to default number of rows with adjustment if rows is set to zero

Adjust number of rows to avoid orphans

---

CDS/src/org/icpc/tools/cds/video/containers/HLSHandler.java

Removes the annoying "Cleaned cache, remaining size:" from logs.

Remove HLS cache cleaning output

---

ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

When we update contest objects on the CDS they're going back through the playback contest, which strips the file references again. Adds a shortcut to add objects to the contest model directly.

Update contest objects directly in the contest

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

Even though we plan on not showing the scoreboard between the two list awards, we do NOT want to highlight them, since that would show them AFTER the award, which is weird.

Do not highlight group winners photo list teams

---

ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

Also add medals in reverse order so resolver displays them correctly when we show two lists just after each other.

Do not count teams double when they have multiple medals

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

Initially we wanted to not show the scoreboard between two 'list' awards. However, this is not true in general. Imagine we want to show a list with all the silver medalists after resolving fifth place, but also a list of all gold medalists just after that. Then we DO want to show the scoreboard in between, since we want to show the highlighted teams. This made me decide to simplify things a lot: add a parameter to indicate whether we show the scoreboard in between. For now, we know this always comes AFTER another list, so we know we do not have to pause in between. I did add a note so we know what to change if that assumption ever changes.

Do not show scoreboard before showing group winners photo screen

---

PresContest/src/org/icpc/tools/presentation/contest/internal/TextImage.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java

It was using an int hash that collided, causing the wrong images to be shown when you change font size (num rows).
Make the header font at most 80% of the size of the row font so that Solved and Time don't overlap (unless you _really_ have lots of rows).

Fix odd font/text in timeline presentation

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/service/MetricsService.java

Adds the /api/metrics endpoint with the following entries:
```# HELP rest_total Total number of REST requests
rest_total{contest="WF22"} 0
feed_total{contest="WF22"} 0
websocket_total{contest="WF22"} 0
webpage_total{contest="WF22"} 0
download_total{contest="WF22"} 0
scoreboard_total{contest="WF22"} 0
desktop_total{contest="WF22"} 0
webcam_total{contest="WF22"} 0
audio_total{contest="WF22"} 0
teams_total{contest="WF22"} 131
problems_total{contest="WF22"} 0
submissions_total{contest="WF22"} 0
```

Promethius metrics

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDetailPresentation.java

It's not a memory leak per se since the JVM _should_ be able to clean them up, but flush images when we're done with them.

Flush images in team detail

---

Resolver/README.md
Resolver/src/org/icpc/tools/resolver/Resolver.java

Updates the resolver documentation to match the recent changes to speed documentation made in #986. Also removed the undocumented --fast equivalent and old javadoc.
Fixes #1065.

Fix resolver speed documentation

---

.github/workflows/ci.yml

The checkout action is old and getting a node warning, update to v4.

Update CI checkout action

---

ContestModel/src/org/icpc/tools/contest/model/internal/Info.java

Support reading REL_TIME penalty times as per the draft spec. Luckily, penalty time was already in ms so we can just try reading the property as an integer or REL_TIME. The tools never read the scoreboard directly, so thats implicitly covered as well.
Server-side / CDS support for the draft spec will come via future PRs.

Client-side support for draft spec REL_TIME changes

---

ContestModel/src/org/icpc/tools/contest/model/internal/Info.java

The draft spec changes contest penalty time to REL_TIME. Support for reading in either old or new format was already added via PR #1078, this adds support for the CDS to output the new format as well. A new ICPC_CONTEST_API system property is added in order to maintain backward compatibility, e.g. add the following to jvm.options to return to the old behaviour: `-DICPC_CONTEST_API=2023-06`.
Support for REL_TIME in the scoreboard will come via another PR.

Event feed support for REL_TIME penalty

---

CDS/WebContent/WEB-INF/jsps/teamSummary.jsp
CDS/src/org/icpc/tools/cds/service/ProjectionScoreboardService.java
CoachView/src/org/icpc/tools/coachview/CoachView.java
ContestModel/src/org/icpc/tools/contest/model/IStanding.java
ContestModel/src/org/icpc/tools/contest/model/Scoreboard.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Ranking.java
ContestModel/src/org/icpc/tools/contest/model/internal/Standing.java
ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
ContestUtil/src/org/icpc/tools/contest/util/EventFeedUtil.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/old/LeaderTickerPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamAwardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/JudgePresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/ScoreboardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
Resolver/src/org/icpc/tools/resolver/awards/AwardUI.java

In the current draft spec, times in the /scoreboard endpoint have been updated to use REL_TIME to match the updated REL_TIME penalty in contest. All ICPC tools can read the new format (#1078), but the CDS does not output in the new format.
The ICPC tools currently store the scoreboard values as integer minutes. Although we could support the new spec by simply converting minutes to REL_TIME (i.e. always end in ':00.000'), this would leave these two values inconsistent and defer support for non-minute penalties down the road (and kind of miss the point).
This PR makes all the underlying changes in order to correctly support different penalties in the future, without breaking current ICPC compatibility:
- Change datatype for time and last solution in standings from minutes to ms.
- Adjust …

Support draft spec REL_TIME in scoreboard

---

PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

This apparently is triggered via KVM in Proxmox where it would otherwise crash with:
```
Exception in thread "main" java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:184)
at org.icpc.tools.presentation.core.internal.PresentationWindowImpl.getCustomCursor(PresentationWindowImpl.java:1177)
at org.icpc.tools.presentation.core.internal.PresentationWindowImpl.<init>(PresentationWindowImpl.java:299)
at org.icpc.tools.presentation.core.PresentationWindow.create(PresentationWindow.java:144)
at org.icpc.tools.presentation.core.PresentationWindow.open(PresentationWindow.java …
```

Never pass through cursor sizes smaller than 1x1.

---

ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java

If you have an award where the top is `solvedTop` and the bottom is an `percentileBottom` and the percentile team is *above* the solved team, you could get indices which would create a list with negative size. In that case, don't create the award.

Handle the case when an honors awards has an empty list

---

ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java

We try to strip the test data count in the public feed by setting it to null, but the property is an integer so you get this in the log instead:
R Error adding property: problems/test_data_count:null
R    java.lang.NumberFormatException: null
R    at org.icpc.tools.contest.model.internal.ContestObject.parseInt(ContestObject.java:142)
This just adds a method to correctly clear the property back to the default value, and uses that.

fix test data count in public feed

---

CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/NDJSONFeedParser.java

Deleting contest objects like runs or submissions was working, but deleting configuration/registration objects like teams or groups is failing. e.g. if you have some groups and use a set in the event feed to replace with a different set, it fails with the following in the log:
R Error adding property: problems/test_data_count:null
R    java.lang.NumberFormatException: null
R    at org.icpc.tools.contest.model.internal.ContestObject.parseInt(ContestObject.java:142)
R Could not parse event feed line: {"type":"groups","token":"...","id": null,"data": [{...},{...}]}
R    java.lang.NullPointerException: null
R    at org.icpc.tools.cds.util.PlaybackContest.applyDefaults(PlaybackContest.java:538)
The fix is in PlaybackContest - we shouldn't try to apply default values to something we're …

Fix error when deleting configuration objects

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java

Before the script would fail on `logo.svg` and never try `logo.png` now it should work based on preference and stop when the resized logo's are correctly created or try a logo with a low preference.

Try all possible logo's

---

CDS/src/org/icpc/tools/cds/CDSConfig.java
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/model/Scoreboard.java
ContestModel/src/org/icpc/tools/contest/model/internal/Info.java

On the main branch the CDS has moved up to the draft spec, but for NAC and Baku we will be running on the 2023_06 spec and there's no target to finalize the current draft. In order to safely run these contests and release the CDS in the interim, the default should be the 2023_06 spec.
This PR:
- Switches the default spec back to 2023_06.
- Changes the system property to 'ICPC_CONTEST_API=draft' in order to use the new/draft spec - the idea being that we always support the current released spec with an option to enable the new draft.
- Adds support to the /access endpoint to return the correct spec version.
- Adds a 'contest-api' property to the cdsConfig to make it easy to switch between specs, e.g. `<cds contest-api="draft" ...`

Default to released spec and change how we handle draft spec

---

ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java

Extraction of the function resulted in failure in generating the background images.
No idea why I didn't catch that when actually testing the extraction.

Pass the correct image to the extracted function

---

CDS/CDS.iml
CDS/README.md
CDS/build.xml
CDS/config/wlp/cds/sentry.properties
CDS/config/wlp/cds/server.env
CDS/config/wlp/cds/server.xml
CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
ContestModel/src/org/icpc/tools/contest/Trace.java

I think this one should be merged before: https://github.com/icpctools/icpctools/pull/1112 as it already implements some of the improvements for that one.
I choose to also raise errors when another system has issues, mostly because those events are important in a contest but might go unnoticed. If this is accepted I can squash the commits but I didn't want to lose progress if changes are requested.

Add Sentry support for the CDS

---

BalloonUtility/BalloonUtility.iml
PresAdmin/PresAdmin.iml
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDisplayPresentation.java
ProblemSet/ProblemSet.iml
Resolver/Resolver.iml

When machines are rebooted after contest the tmp gets lost, we tried storing the temp between reboots but this yields other problems. When observing the log we see that the teamid is correctly found but the floor map data is not available yet (which we need) and the `contestfeed done` log entry is only given later. So we think we're too fast starting the presentation while startup is not done yet.
The other fix is to restart the presentation with the admin (which was the Luxor solution) but this might be a temporary fix.

P100 boots presentation too fast

---

build/cds/Docker/Dockerfile

Ubuntu 20.04 has been EOL since May 2025. This commit upgrades the Ubuntu version to prevent CI from failing.

Upgrade ubuntu from 20.04 to 22.04

---

BalloonUtility/scripts/balloon.bat
BalloonUtility/scripts/balloon.sh
CDS/.settings/org.eclipse.wst.common.component
ContestModel/src/META-INF/MANIFEST.MF
ProblemSet/scripts/problemSet.bat
ProblemSet/scripts/problemSet.sh
Resolver/scripts/awards.bat
Resolver/scripts/awards.sh

When trying to test things on my new machine I found the CDS wouldn't start due to missing sentry library, and two cases where new snakeyaml hadn't been updated.
Most of our batch files use -cp, but these ones used -jar. Switching them over for consistency, and so that we don't to maintain the ones that have versions in the jar name.

Fix dependencies and simplify batch scripts

---

ContestModel/.classpath
ContestModel/src/org/icpc/tools/contest/model/internal/ContestObject.java
ContestModel/src/org/icpc/tools/contest/model/internal/SVGUtil.java
ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java

We had 3 places reading/converting SVGs, with multiple copies of the image transcoder and parsing w/h info. This moves it all to a shared SVGUtil class with only 2 public functions: loading SVGs (2 versions) and converting to BufferedImages.
Since all the work is now done in the model jar the batik jar and its dependencies no longer need to be exported.
Some minor formatting and variable overriding cleanup was automatically applied to the image generator.

Move SVG utility to it's own class

---

BalloonUtility/src/org/icpc/tools/balloon/TeamSummaryPrint.java

Nit in balloon summary: team label is now a required property, teams should be sorted by it instead of the id property.

Sort balloon summary by team label

---

ContestModel/src/org/icpc/tools/contest/model/IJudgement.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Judgement.java

Adds support for the judgement 'current' property as per the draft spec, both read/write and scoring algorithm. Further testing should be done on the scoring algorithm the first time we use 'current' at a contest.

Add support for current judgements

---

CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/FileReferenceList.java

The CDS will repeatedly download 'duplicate' images if the Contest API server says the file is different than what the CDS determines it to be after downloading. For example, if the server says it has an image that's 50x50, the CDS downloads it, and reads it as 51x51, then the next time you restart we'll have a 51x51 image, see that the source has a 'different' one, and download it a second time. This will happen every time the CDS restarts, leading to many duplicate images.
The most obvious solution is to fix the bug in determining image size or file reference data in the CDS or the upstream server, but that takes time and is hard to track down, so this just starts by logging whenever this occurs to make it easier to track. In the future this code would make it easy to take the next step …

Trace when server provides image with duplicate metadata

---

CDS/WebContent/WEB-INF/jsps/teamSummary.jsp

Adds the score to the team summary submissions page to support scoring contests. The scoreboard row is still broken, but I found this minor initial change useful when debugging.

Add submission score to team summary page

---

BalloonUtility/.settings/org.eclipse.core.resources.prefs
CDS/.settings/org.eclipse.core.resources.prefs
CoachView/.settings/org.eclipse.core.resources.prefs
ContestModel/.settings/org.eclipse.core.resources.prefs
ContestUtil/.settings/org.eclipse.core.resources.prefs
PresAdmin/.settings/org.eclipse.core.resources.prefs
PresContest/.settings/org.eclipse.core.resources.prefs
PresCore/.settings/org.eclipse.core.resources.prefs
ProblemSet/.settings/org.eclipse.core.resources.prefs
Resolver/.settings/org.eclipse.core.resources.prefs
SWTLauncher/.settings/org.eclipse.core.resources.prefs

Recent Eclipse versions require you to explicitly set a project encoding instead of relying on the workspace default (which could be different on different machines). Annoying, but just applies the minimal .settings change.

Set Eclipse project encoding

---

CDS/src/org/icpc/tools/cds/CDSConfig.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java

While testing I noticed that when I removed a contest from cdsConfig.xml it correctly disappeared from the web/API, but the background task was still periodically scanning for resource changes in the background.
This just keeps track of the background task and correctly cleans it up when the contest is closed.
I also improved the message so that when you remove a contest from the config it says "Removing baku" (the contest id) instead of "Removing 87384679265" (the internal hash).

Stop background scanning after removing contest

---

ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java

The fix in #1152 fails in many cases due to a casting issue passing a list to FileReferenceList. Fixes that by adding the objects manually.
Also noticed an NPE when a team name is null. Won't happen in a real contest, but currently exists in baku data.

Fix object casting error, NPE

---

ContestModel/src/org/icpc/tools/contest/model/IJudgementType.java
ContestModel/src/org/icpc/tools/contest/model/internal/JudgementType.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/SpectatorContest.java

Adds a new optional property to judgement types, 'simplified_judgement_type_id'. If this is set, any judgements with this type are changed to the simplified judgement type for other teams or anyone who is unauthenticated. (i.e. you can see the detail on your judgements, but not for other teams)
To try this out, set up a contest with a bunch of submissions and judgements, and at least one team account. Create a judgement-types.json in the contest root by capturing the current output of /judgement-types (or just create the content manually). Then add the new property to some of the judgements, e.g.:
```json
[{"id":"OLE","name":"output limit","penalty":true,"solved":false,"simplified_judgement_type_id":"FAIL"},
{"id":"PE","name":"presentation …
```

Experimental support for simplified judgement types

---

CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
CDS/WebContent/WEB-INF/jsps/clarifications.jsp
CDS/WebContent/js/types.js
CDS/WebContent/js/ui.js
CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/IClarification.java
ContestModel/src/org/icpc/tools/contest/model/internal/Clarification.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/account/TeamContest.java

Updates the clarifications table in the CDS web ui to show teams and groups.
If you use a current feed the groups column will always be empty; if you use
the ICPC_CONTEST_API=draft system property then
Introduces better support for array properties. You have to pre-process arrays
using addSeparators() and use {{#array}}content{{/array}} in the template, but
then the objects are automatically separated by line breaks. Award team ids and
any other array properties should be updated to use this (in a separate PR).
Based on #1164, will be rebased once that's in.

CDS web support for clarifications to multiple teams/groups

---

build/builder.Dockerfile
build/website.Dockerfile

The Docker binary defaults to docker.io as registry. Podman as alternative doesn't and might ship with no default registry so can't build this container.
By explicit specifying the registry the risk for inconsistent builds is also decreased in case the GHA ever encounters a similar named container on the GHCR and would not use docker.

Specify which registry to trust

---

BalloonUtility/README.md
CDS/README.md
CoachView/README.md
ContestUtil/README.md
Resolver/README.md

It seems its not part of the spec according to: https://www.markdownguide.org/hacks/#image-size
I checked with the GitHub page itself and it seems it also ignores the width:
and in the PDF (generated on linux):
So I think we can close: https://github.com/icpctools/icpctools/issues/775 as the width probably worked in the past but doesn't anymore (or I just don't see what it should do).
Closes: #775

Remove {width} as its not in spec

---

PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java

Adds an option to set a default presentation for connected presentation clients. This presentation is set before trying to connect to the CDS. If the CDS doesn't set any presentation then this one is shown; otherwise whatever the CDS says takes over.
This avoids the standard ICPC Tools splash page, and allows you to have a default w/o waiting for clients to connect and then setting it in the pres admin.
Fixes #955.

Default presentation for presentation client

---

PresAdmin/scripts/presAdmin.bat
PresAdmin/scripts/presAdmin.sh

The Sentry jar was not found and although it doesn't use it yet it needs to find it because of the ContestModel providing Sentry config.

Fix start of PresAdmin

---

ContestModel/src/org/icpc/tools/contest/model/internal/ContestObject.java

There's a very small chance that an SVG just contains a low res image, but in all other cases SVGs are better: the file download time is less, loading is less, and generating an image of any exact size should be comparable to png scaling. This change always picks an SVG as 'best' if one exists in a file reference list, regardless of requested image size.

Always prefer SVGs

---

PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java

The display size allows you to configure a portion of the screen for display, e.g. for cropping an overwash edges for projectors. It was getting reset when new presentations are setup, this fixes that.

Consistently use display size

---

CDS/src/org/icpc/tools/cds/service/ContestWebService.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
CDS/src/org/icpc/tools/cds/video/VideoServlet.java

Fix the video urls broken from a previous PR. When there's no file it should be "http://stream/6", not "http://stream/6/null". :)

Fix non-file video urls

---

CDS/WebContent/WEB-INF/jsps/details-admin/contest.html
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

Found while testing with Pavel's contest API:
- unnecessary console output in CDS web
- contest without a freeze causes NPE in the resolver

Remove unnecessary output

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java

Closes #1171,
I'm not 100% if the logo is now placed in the same location or if the `x` should be calculated differently but on first glance this looks like a fix.
I've added 2 commits, for both possible solutions.
I like the 2nd for the consistency
The first has the benefit of giving more space for the name which might be worth it as the logo is already on screen at that moment.

World map logo ratio

---

PresAdmin/src/org/icpc/tools/presentation/admin/internal/CompositePresentationDialog.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/CompositePresentationSaveDialog.java
PresAdmin/src/org/icpc/tools/presentation/admin/internal/View.java

- Combines the composite presentation setup dialog and its save dialog.
- Enables editing composite presentations, and duplicating them by choosing a new name

Add composite presentations in a single dialog and enable editing

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java

Team intro throws an NPE when there's a team that isn't in any groups - in our case due to bad data, but we should avoid the NPE.

Team intro presentation fails when teams are missing data

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDetailPresentation.java

The team intro/detail presentation expected every team to have a photo. With this change if there's no photo it'll just display a bigger logo.

Avoid NPE if team detail has no photo

---

PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDetailPresentation.java

If the team detail (intro) presentation has both photo and logo, the logo goes at the top right of the photo. If the screen is too narrow (wider than it is high) the logo can be drawn partially off the top of the screen. This just moves it down in this case.

Always keep team detail logo onscreen

---

Resolver/src/org/icpc/tools/resolver/Resolver.java

Do the same taskbar fix to the resolver as we've done elsewhere. Bump up the timeouts to reflect how long modern contests with logos take to load.

Resolver fixes

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

The CDS stores a set of 'default' objects as it reads config from disk, and then when it gets objects from the CCS that match it adds any missing properties. When the contest data was requested by multiple accounts before the default configuration was loaded, the configurationLoaded flag can get triggered early.
Remove unused configType = false code path and only store config objects in the default config.
Make the 'end of configuration' more direct: just call the contest.setConfigurationLoaded() method directly from the disk source instead of triggering off an event.
Remove unused filterHidden() method to reduce confusion.

Improve default config

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java

Avoid serving data to non-admin clients until we've loaded all configuration files from disk, to avoid the situation where we load the tsvs, allow some clients to see them, and then load the jsons.

Delay non-admin contest feeds until configuration is loaded

---

CDS/src/org/icpc/tools/cds/ConfiguredContest.java
CDS/src/org/icpc/tools/cds/util/PlaybackContest.java

Fixes two problems:
- PlaybackContest had its own configurationLoaded property, which never gets set: all non-admin clients would wait for 2s regardless of config being loaded. It now uses the property from the parent contest object.
- Synchronized accountContests means that the playback contest is blocked from adding objects while we're waiting for account to load... which blindly waits for 2s as per above. i.e. we weren't letting the main contest load config at all. It now spreads the objects to each account directly (multiple listeners) instead of from the main listener.

Fix loading synchronization issue

---

ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamAwardPresentation.java
PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java

Adds support for a parameter ("afterId") to allow awards to 'resolve after' another award or scoreboard row.

Resolve after

---

ContestModel/src/org/icpc/tools/contest/model/FloorMap.java

When a floor map is saved to disk it automatically moves the origin to top left, just to pretty-print values and have 0,0 at the top left. Unfortunately it was missing spares (empty desks) when doing this, so they were always 'off the map'.

Include spares when reseting contest floor origin
