- .gitlab-ci.yml
- README.md
- website/content/_index.md
Before merging this we can rename master to main, it will then sync to GitLab.
The only thing left after that and merging this should be to manually change the setting on GitLab.
> Rename master to main in CI, readme and website.

- version.properties
> Update version after release

- ContestModel/src/org/icpc/tools/contest/model/util/ArgumentParser.java
Changes made 21 days ago to fix parsing of int/float options containing 'e' broke parsing of floats, fixing that. Fixes issue #307.
> Fix parsing of float args

- ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
- Resolver/src/org/icpc/tools/resolver/Resolver.java
Group awards weren't working in the Award UI due to the wrong constructor being called.  Also fixing some odd formatting from my last commit.
> Group awards not assigned

- Resolver/src/org/icpc/tools/resolver/Resolver.java
As discussed on the CLICS call, the resolver should only check for contest finalization, not being done updating.
> Resolver should only block on finalization

- CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
Initial support for posting clarifications and acting as a proxy to a CCS.
> Clarification POST support

- ContestModel/src/org/icpc/tools/contest/model/internal/Team.java
Missed a critical class in last commit. :)
> Ability to set display name

- website/content/_index.md
- website/content/coach-view.md
- website/content/pres-admin.md
- website/content/problem-set-editor.md
> Fix references to old CLI spec wiki

- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
Instead of assuming the API of external CCS'es always starts with /api/, determine the real URL by using a regex on the CCS URL.
Kattis uses /clics-api/contests/xxxxx for a contest so it broke there if they use relative URL's.
Also use the root of the URL instead of the part before /api/ for absolute URL's, since I think that is what is meant in the spec.
@SuprDewd found this issue 😄.
> Determine base URL of API correctly.

- CDS/WebContent/WEB-INF/jsps/details-admin/judgementTypes.html
- CDS/WebContent/WEB-INF/jsps/details-admin/problems.html
- CDS/WebContent/WEB-INF/jsps/details.jsp
- CDS/WebContent/WEB-INF/jsps/details/judgementTypes.html
- CDS/WebContent/WEB-INF/jsps/details/problems.html
- CDS/WebContent/WEB-INF/jsps/scoreboard.jsp
- CDS/WebContent/WEB-INF/jsps/submissions.jsp
- CDS/WebContent/css/cds.css
- CDS/WebContent/js/types.js
- CDS/WebContent/js/ui.js
A few UI improvements to make things a bit cleaner and better looking:
- Change problem labels to coloured badges.
- Judgement types - change id to coloured badge, and Penalty and Solved columns to checkmark/X badges.
- Submission - switch to use new problem badge.
- Scoreboard - start using templates for most <td>s, and switch problem header to new badges.
- Details page - for teams, move teams and orgs into the same row to use the space better.
> Prettier problems and judgement types, scoreboard templating

- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
Handle redirects on base contest URL, make redirects more consistent, and handle 307/308 status the same way
> Support redirects on contest URL

- CDS/WebContent/js/types.js
Clarification text isn't split over lines correctly and fixed a bug in award table.
> Minor UI fixes

- CDS/WebContent/js/contest.js
- ContestModel/src/org/icpc/tools/contest/model/ICommentary.java
- ContestModel/src/org/icpc/tools/contest/model/IContest.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Commentary.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
Adding API for commentary to both the Java and Javascript contest models
> Commentary API

- CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
- CDS/WebContent/WEB-INF/jsps/clarifications.jsp
- CDS/WebContent/WEB-INF/jsps/commentary.jsp
- CDS/WebContent/WEB-INF/jsps/details-admin.jsp
- CDS/WebContent/WEB-INF/jsps/details.jsp
- CDS/WebContent/WEB-INF/jsps/layout/head.jsp
- CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
- CDS/WebContent/WEB-INF/jsps/registration.jsp
- CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
- CDS/WebContent/WEB-INF/jsps/submissions.jsp
- CDS/WebContent/js/types.js
- Add commentary page for admins.
- Add team logos to submissions page.
- Fix API link on clarifications-admin.
- Remove unnecessary JSP imports & IState from several pages.
- Fix NPE in language extension when attribute doesn't exist.
> Commentary page, fixes

- CDS/WebContent/WEB-INF/jsps/clarifications.jsp
- CDS/WebContent/js/contest.js
- CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
A simple form for teams to submit clarifications. A drop down allows problem selection (or none) and text entry.
> Team clarification submission

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/CommentaryPresentation.java
Parses commentary messages into a list of strings, teams, and problems, and painting these separately, with logos for teams (if they exist) and problem badges. It still needs UI improvements and work (e.g. it doesn't wrap messages that are too long), but it is starting to look better.
> Parsing & painting commentary

- CDS/WebContent/WEB-INF/jsps/clarifications-admin.jsp
- CDS/WebContent/WEB-INF/jsps/clarifications.jsp
- CDS/WebContent/WEB-INF/jsps/commentary.jsp
- CDS/WebContent/WEB-INF/jsps/details-admin.jsp
- CDS/WebContent/WEB-INF/jsps/details-admin/contest.html
- CDS/WebContent/WEB-INF/jsps/details-admin/judgementTypes.html
- CDS/WebContent/WEB-INF/jsps/details-admin/languages.html
- CDS/WebContent/WEB-INF/jsps/details-admin/problems.html
- CDS/WebContent/WEB-INF/jsps/details/contest.html
- CDS/WebContent/WEB-INF/jsps/details/judgementTypes.html
- CDS/WebContent/WEB-INF/jsps/details/languages.html
- CDS/WebContent/WEB-INF/jsps/details/problems.html
- CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
- CDS/WebContent/WEB-INF/jsps/registration.jsp
- CDS/WebContent/WEB-INF/jsps/submissions-admin.jsp
- CDS/WebContent/WEB-INF/jsps/submissions.jsp
Cleanup of unused accordion containers, data-toggles, and text alignment
> HTML cleanup

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/CommentaryPresentation.java
Improved parsing, added basic support for multi-line messages (wraps on segments, like start/stop of team or problem), and cleaned up unused code from the original judge presentation.
> Fixed commentary parser, initial line wrapping, cleanup

- ChangeLog.md
- version.properties
Update build version and first pass at updating change log for the next release.
> Bump version, changelog

- Resolver/src/org/icpc/tools/resolver/Resolver.java
John was confused by log messages, making these more obvious
> Improve logs for --groups and --problems

- BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
There is no direct support for SVGs in SWT, so using a conversion from AWT to make it work
> Balloon printer support for SVGs

- ContestModel/src/org/icpc/tools/contest/model/IContest.java
- ContestModel/src/org/icpc/tools/contest/model/ISubmission.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Submission.java
Add an optional attribute for Moscow WF, allowing a submission to be associated with which team member submitted it.
> Submission team member

- CDS/WebContent/WEB-INF/jsps/layout/head.jsp
- CDS/WebContent/WEB-INF/jsps/video.jsp
- CDS/src/org/icpc/tools/cds/ConfiguredContest.java
- CDS/src/org/icpc/tools/cds/service/ContestWebService.java
- CDS/src/org/icpc/tools/cds/video/VideoAggregator.java
- CDS/src/org/icpc/tools/cds/video/VideoServlet.java
- CDS/src/org/icpc/tools/cds/video/VideoStream.java
- CDS/src/org/icpc/tools/cds/web/ChannelControlServlet.java
Ok, here's an updated admin page allowing more than one stream per team. Made some minor UI and stats improvements while getting it working. The stream #s are colour-coded to show failures and streams successfully streaming.
> Video admin for multiple streams

- CDS/README.md
- PresContest/README.md
Updated the documentation to support the hosts element and related changes in order to stream multiple videos per team. While I was there I noticed some other minor issues and fixed them (e.g. reaction videos are now variable-length).
> Update docs with host element

- CoachView/src/org/icpc/tools/coachview/CoachView.java
Coach view support for multiple desktop and webcam streams per team. If there are multiple streams for a team they are shown as two entries in the list, e.g. "UBC (1)" and "UBC (2)". Selecting either will give the first pair of webcam/desktop or second. If the number of webcams and desktops don't match, the maximum number of options are shown and you'll only see the one stream that exists for those options.
> Coach view support for multiple streams

- ContestModel/doc.sh
- PresContest/README.md
Local tests indicate that these two changes should improve the parsing of the git markdown and likely fix the table rendering in the PresContest docs
> Change formatting for pdf

- CDS/src/org/icpc/tools/cds/presentations/Client.java
Two minor improvements that I had sitting in my workspace for a while: If we've had two fast pings, don't bother with a third. Don't bother sending time sync if it's < 20ms difference
> Minor time sync improvements

- ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGenerator2020.java
Updated to match the current floor diagram, along with a couple minor fixes
> 2020 floor map

- CDS/src/org/icpc/tools/cds/service/ResolverService.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
Fix build break (missing change) and remove unnecessary trace output
> Fix build break

- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/AbstractTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TilePictureScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileScoreboardPresentation.java
Several small changes to improve the look and animation for the tile presentations
> Tile presentation improvements

- PresContest/src/org/icpc/tools/presentation/contest/internal/TextHelper.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/AbstractTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TilePictureScoreboardPresentation.java
Cache text helper and use images for problem boxes.
> Tile presentation performance improvements

- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
Cache team name and problem results as images.
> Tile perf 2

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/feed/JSONEncoder.java
Fix downloading of folder listings, e.g. presentation/build images.
> Fix folder listings

- ContestModel/src/org/icpc/tools/contest/model/internal/Organization.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/JudgePresentation.java
Fix lat/long NaN issues for team intro, and team name valign on judge queue
> Minor presentation fixes

- PresContest/src/org/icpc/tools/presentation/contest/internal/ClientLauncher.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/CCSPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/DoNotTouchPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/MessagePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/ClockPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/CountdownPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/StatusCountdownPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/test/FPSPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/test/MessagePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/test/TestAlignmentPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/test/TestClockPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/StandaloneLauncher.java
- PresCore/src/org/icpc/tools/client/core/BasicClient.java
- PresCore/src/org/icpc/tools/presentation/core/Presentation.java
- PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
Support for --light in the presentation clients and some of the easier presentations. Minor simplifications for time syncing.
> Light mode

- CDS/src/org/icpc/tools/cds/presentations/Client.java
- CDS/src/org/icpc/tools/cds/presentations/PresentationServer.java
Nano time is drafting, reduce the ping frequency but sync time every 5 minutes.
> Continuous time sync

- ContestModel/src/org/icpc/tools/contest/model/IAward.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Award.java
- ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
- Resolver/src/org/icpc/tools/resolver/awards/EditAwardsDialog.java
- Resolver/src/org/icpc/tools/resolver/awards/TemplateAwardDialog.java
Changes:
- Add an award display mode to not stop at an award, and add a method to tell if the mode is set.
- Update award util to respect the display mode on most templates.
- Fix edit award dialog.
> Award util updates

- CDS/src/org/icpc/tools/cds/presentations/Client.java
- CDS/src/org/icpc/tools/cds/presentations/PresentationServer.java
Add a method to schedule time syncing immediately, and call it whenever we sync the time.
> Sync time immediately

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDisplayPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/standalone/TeamUtil.java
> Add team ID and member to TeamDisplayPresentation.

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ICPCTeamPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/MessagePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/PolarCountdownPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/StatusCountdownPresentation.java
- PresCore/src/org/icpc/tools/presentation/core/Presentation.java
- PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
Additional tweaks to support light mode.
> Light mode fixes

- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/AbstractTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileRankScoreboardPresentation.java
Fix cutoff text in tile scoreboards, and add light mode while we're at it.
> Fix cutoff text in tile scoreboards

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/CountdownPresentation.java
To catch the lightMode property.
> Call super set property in countdown

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ICPCTeamPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/WavePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
Memory and minor uI improvements to the tile presentations. Also speed increase in two others.
> Tile presentation memory improvement

- CDS/src/org/icpc/tools/cds/video/VideoServlet.java
> Add CORS to stream endpoints.

- ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGenerator2020.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/floor/BalloonFloorPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/floor/ContestFloorPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/old/FloorNamePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/old/FloorPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/FirstSolutionPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
- Floor presentations - fix team id rotation.
- Floor map - react to shift in positions.
- Tile presentation - fix summary box widths to match the teams.
- First to solve - fix team name max width.
> Presentation fixes

- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ImageBuildPresentation.java
- Resolver/src/org/icpc/tools/resolver/Resolver.java
- Resolver/src/org/icpc/tools/resolver/TeamAwardPresentation.java
- Resolver/src/org/icpc/tools/resolver/TeamListPresentation.java
Avoid hang when team awards aren't sorted, and minor tweaks to flow and UI.
> Resolver fixes

- CDS/src/org/icpc/tools/cds/CDSConfig.java
- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
CDS name is picked up from config folder (e.g. "cds","resolver","live") or can be explicitly set by <cds name="tim"> in cdsConfig.xml.
> CDS naming!

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/clock/CountdownPresentation.java
Use Long to avoid int overload
> Fix target countdown time

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ProblemSummary.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ProblemSummaryPresentation.java
Scales with number of problems, and cleaner UI.
> Better problem summary

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ProblemSummaryPresentation.java
Remove test colour for problem 2 and fix summaries.
> Problem summary fixes

- CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java
The url should be everything but the last five characters, not only the last five...
> Fix reaction video name

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamAwardPresentation.java
Fix for team name emojis on award screen, also allows citations
> Team Award Emojis

- PresContest/src/org/icpc/tools/presentation/contest/internal/Legend.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/TimelinePresentation.java
Minor improvements to legend and timeline presentation
> Light mode nits

- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/ScrollingTileScoreboardPresentation.java
Fix contest time fitting on left header of tile scoreboards
> Contest time fit

- CDS/WebContent/WEB-INF/jsps/details/judgementTypes.html
- CDS/WebContent/js/ui.js
A few improvements to table sorting: sort alphabetically by default, change cursor to indicate sorting, and show sort indicators.
> Improve table sorting

- ChangeLog.md
- PresContest/README.md
- Resolver/README.md
Update the readmes to add light mode and catch changelog up to current status.
> Update readmes, changelog

- README.md
- doc/spec-extensions.md
Documented all the spec-extensions that the tools support, along with examples.
> Spec extensions

- ContestModel/src/org/icpc/tools/contest/model/feed/JSONParser.java
Bug found via Fredrik: parsing failure when a JSON value ends in `\\"`. Currently it is trying to find the complete value by looking for a `"` that isn't preceded by a `\`, but this fails when the slash is part of a previous special char like `\\`.
Changed to parse JSON values as it goes instead of trying to find the end token and then unescaping the complete value. This allow it to correctly find special chars as it goes, and has a side effect of speeding up JSON parsing by about 4x in my tests. Although this is somewhat counter-intuitive, it looks like creating a string builder as it goes is cheaper than scanning once to find the end, creating a string, and then going back to look for special chars.
Minor improvements to unescape() method to avoid creating temporary array, which may …
> Fix JSON parsing of special chars

- ContestModel/src/org/icpc/tools/contest/model/IProblem.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
Add problem uuid, which I missed earlier.
> Problem UUID

- CDS/WebContent/WEB-INF/jsps/contestAPI.jsp
- CDS/WebContent/WEB-INF/jsps/welcome.jsp
- Resolver/README.md
- Fix the Contest API url
- Fix the contest path from the welcome page
- Fix resolver --singleStep example
> Minor fixes

- ContestModel/src/org/icpc/tools/contest/model/internal/Language.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Location.java
Adding language compiler and runner, which were added to the Contest API a while ago. I'm not going to bother adding API for them for now, since they are informational and don't know of any clients that would use it.
> Language compiler and runner

- ContestModel/src/org/icpc/tools/contest/model/IAccount.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Account.java
Rename the account people_id to person_id, to match the spec (even though the rest doesn't, at least this won't be missed later).
> People -> Person

- CDS/WebContent/WEB-INF/jsps/registration-admin.jsp
- CDS/WebContent/js/contest.js
- CDS/WebContent/js/types.js
Adds accounts and persons to the JS contest model and admin registration page. Doesn't do anything special with the formatting for now, just gets the data there.
The data might be mildly interesting, but I didn't add for non-admin users.
> Accounts and Persons UI

- ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
Thanks @vmcj for finding this!
> All organizations are public data.

- ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
Also expose balloons to draw paths during testing.
> Expose full bounds to presentations for floor map.

- CDS/src/org/icpc/tools/cds/ConfiguredContest.java
> Fix team video streams

- ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
> Fix languages

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
Support for event-feed.ndjson as per the spec, retaining backward-compatibility
> event-feed.ndjson

- BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
No screencap - just imagine skinnier team numbers.
> Shrink long team numbers to fit balloon printout

- ContestModel/common.xml
- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
- ContestUtil/src/org/icpc/tools/contest/util/cms/GoogleMapsGeocoder.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/NLS.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/BubbleOut.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/TeamIntroPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/map/WorldPresentation.java
- PresCore/src/org/icpc/tools/client/core/BasicClient.java
- Resolver/src/org/icpc/tools/resolver/awards/AddAwardDialog.java
- build/builder.Dockerfile
A bunch of minor fixes that have been sitting around in my workspace and don't seem worth PRing separately:
- Standard formatting
- Use Trace class
- Fix a Java deprecation warning
- Contest model: only try to download file ref hrefs that are http
- Allow trailing slash on presentation admin url
- Make 'add award' dialog combo uneditable (since it isn't)
- A couple coding nits
> Random fixes

- ContestModel/src/org/icpc/tools/contest/model/feed/NDJSONFeedLogParser.java
- ContestModel/src/org/icpc/tools/contest/model/feed/NDJSONFeedParser.java
- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
Support for the new event feed notification format (no 'op', notifications can be single object or arrays), without dropping support for the previous event feed format.
> Notifications event feed

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/NetworkUtil.java
Some random fixes:
- 2 missing null checks
- Missed caching the local address in one scenario
- Don't output password in toString() so it doesn't end up in logs
> Assorted minor fixed

- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
I added 'if (!href.startsWith("http"))' a few weeks ago to avoid the case where a local event feed included file reference urls and this was causing it to try to download weirdly named files, causing lots of errors in logs. Unfortunately, it was causing relative URLs to be skipped as well.
The correct fix is in getResolvedURL(), but along the way I noticed that it was only being used in createConnection() from one caller, so inlined that and removed the boolean argument, simplifying other calls to createConnection().
> Improve relative URL detection

- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorNAC22.java
> NAC22 floor map

- BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
Having some printing problems on linux, this is a guess at what might be causing odd print scaling issues
> Skip resetting transform

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/ProblemSummaryPresentation.java
Fix the problem summary presentation to show the correct number of boxes for all values of 'numProblems'...
> Problem summary not showing all problems

- .github/workflows/ci.yml
Thanks @troy2914 for the commands, this uses cURL so we can retry failed uploads.
> Use curl to upload assets so we can retry

- ContestModel/src/org/icpc/tools/contest/model/internal/Run.java
Run time property can be 0, change the default to -1.
> Fix Run run_time

- ContestModel/src/org/icpc/tools/contest/model/ICommentary.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Commentary.java
Recent-ish spec addition that I added and forgot to PR.
> Add submission ids to commentary

- ContestModel/src/org/icpc/tools/contest/model/IContestObject.java
- ContestModel/src/org/icpc/tools/contest/model/IPerson.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Person.java
Add support for person's teamIds array. Not required soon, but I prefer to update compatible support as it happens to avoid missing things later. Minor fix to contest object to avoid Eclipse warning (and simpler code).
> Person team_ids array

- ContestModel/src/org/icpc/tools/contest/model/TSVImporter.java
- ContestUtil/src/org/icpc/tools/contest/util/cms/JsonToTSVConverter.java
- ContestUtil/src/org/icpc/tools/contest/util/cms/TSVImporter.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorDhaka.java
Making some minor changes while dealing with Dhaka config:
- Work around the CMS extra column in institutions2.tsv in a different way.
- Simplify argument processing in JsonToTSVConverter, b/c I found a case where --finals was not being picked up.
- Update floor generator for new floor layout.
> Dhaka config updates

- CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
- ContestModel/src/org/icpc/tools/contest/model/internal/FileReferenceList.java
- doc/ChangeLog.md
- Backups should not be accessible except to analyst (or above).
- Hit a problem casting FileReferenceList, fixing conversion.
- Updated change log.
> Minor fixes & updates

- CoachView/src/org/icpc/tools/coachview/CoachView.java
The coach view has had some of the initial support to watch reaction videos for a couple years, but I never finished the support. This completes it with the ability to click on any submission in the details view that has a reaction and it will play. The usability is not obvious, but that's ok b/c I don't want to advertise this support until we've had a chance to test on a real-ish contest, possibly after Dhaka. Half of this change is also renaming some of the old variable names to 'webcam' and 'desktop' to match the spec and adding a 'mode' and clearMediaPlayer() to clean up the code paths.
> Coach view reaction support

- CoachView/src/org/icpc/tools/coachview/CoachView.java
As requested for World Finals.
> Change country to group in coach view

- ContestModel/src/org/icpc/tools/contest/model/feed/RESTContestSource.java
When downloading files from a source, there can be collisions (race condition) if there are multiple processes (CDSs) writing to the same folder. If one CDS is slightly faster, then the next one may delete and redownload the file (leaving no file for a second) or two could write to the same file at the same time. The final result is fine on disk, but either CDS could have periods where the file they just wrote doesn't exist for a second.
Solves this issue by downloading to a temp file and renaming. If the file exists by the time you're done with the correct timestamp it avoids replacing it.
> Avoid download collision

- PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
There's an NPE that we've hit in Dhaka a few times b/c both the main painting thread and the thumbnails can update the presentation state (current presentation plan) at the same time, and possibly setting it null while the other thread is still using it. Avoids this by using a temporary variable. Includes an unrelated change to update the window title with each presentation update.
> Fix presentation window NPE

- BalloonUtility/src/org/icpc/tools/balloon/BalloonPrinter.java
Tweaks to avoid overlapping and look better on A4.
> Balloon print improvements

- PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
See the link I referenced, this seems to 100% fix the issue I was having with the fullscreen presentations not working and it doesn't seem to hurt.
> Fix strange bug with macOS fullscreen.

- Resolver/src/org/icpc/tools/resolver/Resolver.java
Add a second undocumented parameter to the resolver, allowing problem filtering by problem id. You know, just in case there was a contest crazy enough to have duplicate problem labels.
> Allow resolver filtering by problem id

- ContestModel/src/org/icpc/tools/contest/model/internal/NetworkUtil.java
> Local IP for tools like Presenter may be read from env var

- CDS/WebContent/js/cds.js
- CDS/WebContent/js/model.js
- CDS/WebContent/js/types.js
Fixes three issues in the CDS web client:
- cds.js wasn't setting the mime/content type correctly, which resulted in failed POSTs.
- model.js couldn't handle null/missing contest time, so if time was missing from any element there was an error.
- types.js would fail if commentary was missing the problem ids or team ids attribute.
> Web client fixes

- ContestModel/src/org/icpc/tools/contest/model/internal/ContestData.java
The method removeFromHistory fails when the ContestData contains IDelete/Deletion objects.
The reason is an incorrect rebuilding of the type caches: the IDelete objects should delete the objects from the cache (as it does when these IDelete objects are regularly added to the ContestData). Instead of that , they are inserted (again) to the cache and the cache array does not have enough space.
See #773 for an use case.
The PR/fixed includes two auxiliar methods to add/update or remove objects from the typed cache that are used in removeFromHistory and other public methods.
> Fixed ContestData::removeFromHistory

- PresCore/src/org/icpc/tools/presentation/core/DisplayConfig.java
- PresCore/src/org/icpc/tools/presentation/core/internal/PresentationWindowImpl.java
Make visibility issue Mac specific, add 't' mode for testing that will allow you to pick any display config
> Make visibility issue Mac specific, add test display graphics mode

- CDS/src/org/icpc/tools/cds/presentations/PresentationWebSocket.java
Hopefully this helps reduce hung clients staying for long periods of time.
> Set send timeout for CDS web socket

- ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
- Resolver/src/org/icpc/tools/resolver/awards/TemplateAwardDialog.java
Support in the template for adding an award for groups of teams that solved the same number of problems.
Fix median when there is an odd number of teams.
> Solution awards & median fix

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Info.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
- ContestModel/src/org/icpc/tools/contest/model/internal/YamlParser.java
Found while creating a sample contest package.
> Models / YAML parser: fixes for problem statement+package and contest location/

- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
This change does two things:
- adds support for loading contest objects as default objects (required for a different PR that's coming).
- switches from storing default objects in an array to using a Contest.
'Defaults' are config loaded from disk that should always provide default properties from anything coming 'live'. This is what allows us to load things like org logos from disk even if the CCS doesn't support them. When we get the object from the CCS we simply add default values for any properties that weren't set.
Storing these objects in an array has always been a performance bottleneck, because if you loaded over 1000 items from disk (140 teams, 140 orgs, 800 people, 15 problems, 10 judgement types, some groups and languages), you need to scan through all 1000 items later to …
> Use Contest for storing defaults

- CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java
Records both webcam and desktop streams for reaction videos, naming the files differently on disk and including both in file refs. Removes future var, since it was never read.
> Record desktop reaction videos

- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorDhaka.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorSharm46.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorSharm47.java
Initial team floor generators for Sharm 46 & 47 contests.
> Initial Sharm floor generators

- ContestModel/src/org/icpc/tools/contest/model/IContest.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Contest.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Info.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Result.java
For consistency penalty should be a Long, plus this sets the stage for the next spec version.
> Long penalty values

- website/content/_index.md
Suggest we put something like this on the website for now...
> Website warning

- ContestModel/src/org/icpc/tools/contest/model/internal/account/AnalystContest.java
> Add submission files and entry point for analysts.

- CDS/src/org/icpc/tools/cds/video/VideoAggregator.java
- CDS/src/org/icpc/tools/cds/video/VideoStream.java
- CDS/src/org/icpc/tools/cds/video/containers/HLSFileCache.java
- CDS/src/org/icpc/tools/cds/video/containers/HLSHandler.java
- CDS/src/org/icpc/tools/cds/video/containers/HLSParser.java
Next pass at HLS support:
- Changed the VideoAggregator so it doesn't create a massive thread pool if we have a serving handler.
- Changed VideoStream to pass execution requests back to the aggregator instead of holding onto a reference to the thread pool.
- Implemented a background thread to clean up the HLS cache, currently running every 5s and removing any file that hasn't been downloaded (in either direction) for 20s. [*]
- Added support for HLS X-GAP, so that we're not dependent on the name of the gap file.
[*] On my machine the cache for a single stream can get up to 27Mb, which if you do the math would run out of CDS memory in Sharm. But, we have no idea what the bitrate is that we're going to use or how many concurrent streams, so we can tune the cache or deal with this later...
> HLS memory cache cleanup & X-GAP support

- CDS/src/org/icpc/tools/cds/video/containers/HLSFileCache.java
- CDS/src/org/icpc/tools/cds/video/containers/HLSHandler.java
Added:
- Minimal support for HLS preload files. It works, but may download the file more than once if there are multiple clients.
- Most basic HLS index caching; if the file is requested without query params we can return the latest copy we have. This helps initial response time but likely no requests after that.
- Removed TODO for gap.mp4, which was done in previous commit.
- Some code cleanup.
> HLS: preload support and basic index caching

- ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
Three changes to image generator:
- Load contest logo from the CPF location (with old fallback for now).
- Instead of trying to load the main org logo from disk, use the contest model. First, this means we're using exactly what any of the other tools will see (like CDS) at runtime and will find issues earlier, second, it means we might get a pre-scaled version which will be faster, and third, its more likely to work when the CMS has an odd filename.
- Reload the contest model before generating the previews, so that we pick up any changes we just made.
> Image generator - use contest images

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
> Mime-type check shouldn't be case sensitive

- CDS/src/org/icpc/tools/cds/service/ResolverService.java
Update resolver service to remove the old properties and work per-contest. Add reset action to set resolution back to first step and default options.
> Update resolver service

- PresContest/src/data/firstsolutions.txt
> Add first solutions for 2020 and 2021

- ContestModel/src/org/icpc/tools/contest/model/IAward.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Award.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
- PresContest/src/META-INF/presentations.xml
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java
- Resolver/src/org/icpc/tools/resolver/ResolverUI.java
- Resolver/src/org/icpc/tools/resolver/awards/AddAwardDialog.java
- Resolver/src/org/icpc/tools/resolver/awards/EditAwardsDialog.java
Adds support for showing an award for multiple teams as a set of photos instead of a list.
> Resolver award photos

- ContestModel/src/org/icpc/tools/contest/model/util/AwardUtil.java
This is useful if you want both individual medals but also a photos one. ID's do need be unique and end in -medal for this to work.
> Allow more than one of each medal awards.

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/TeamDisplayPresentation.java
This makes it such that we show something if we have no team.
> Always preload contest image even if we have no team.

- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/resolver/TeamListPhotoPresentation.java
Tweaks to team photo list:
- use contest logo if there's no photo
- actually load org logos
- reduce size of text
> Improve team photo list

- Resolver/src/org/icpc/tools/resolver/Resolver.java
The contest source, final contest, and presentation client were using a single variable, so when you had a multi-contest there was no guarantee that resolution events or properties were being sent to the correct one. This just keeps the variables separate per-contest as we do with the UI.
> Separate multi-contest data

- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
Allow awards to be given 'before resolving row x' using the syntax
"parameter":"before:X". Removes sorting awards, we just evaluate before
and after each step to determine if there are any team list/photo awards
to give.
> Support for "before row X' list/photo awards

- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
Allow multiple lists after we're done resolving a row, so that we can (e.g.) have a solution award after resolving row 13 but then display the medalists next before selecting 12. Change the before:12 to actually go after 13, because 'before' is actually in the wrong place (future issue).
Allow HM awards to also use the parameter:5 to trigger after all teams have solved more.
> Fix HM and medalists timing

- website/layouts/shortcodes/allbuilds.html
- website/layouts/shortcodes/lastbuilds.html
- website/layouts/shortcodes/tooldownload.html
- website/scripts/populate-releases.py
> Add build time and commit to website.

- ContestModel/src/org/icpc/tools/contest/model/internal/Ranking.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Standing.java
Add support for sorting & ranking teams in scoring contests. Sorting is based on score and then ranking is applied from the top with ties for any teams that have the same score.
> Support for ranking scoring contests

- ContestModel/src/org/icpc/tools/contest/model/ContestUtil.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/nls/Messages.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/nls/Messages.properties
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/AbstractScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/ScoreboardPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/SingleTeamPresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/TimelinePresentation.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
Support for scoring contests on the main presentation scoreboards:
- individual scoreboard cells show number of attempts when unsolved, and score when solved.
- Replacing Solved + Time columns with Score column (and give more space to the team name).
> Presentation scoreboard support for scoring contests

- PresContest/src/org/icpc/tools/presentation/contest/internal/chart/JudgeQueueDepthChart.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/chart/JudgementChart.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/scoreboard/FirstToSolvePresentation.java
Should just switch to the existing key in translated messages so that anyone could translate these too.
> Use translations

- ContestModel/src/org/icpc/tools/contest/model/FloorMap.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorLuxor46.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorLuxor47.java
Final floor map generator from Luxor, with a utility method that will compare against the real contest and convert any teams that are missing into spare machines.
> Luxor floor maps

- Resolver/src/org/icpc/tools/resolver/Resolver.java
> Pass speed to inner resolvers

- Resolver/README.md
Minor updates to the docs:
- Correct names for me and KTH
- Change `--fast` to `--speed` to match `--help`. (Both are allowed/correct).
> Minor updates to resolver docs

- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGenerator.java
- ContestUtil/src/org/icpc/tools/contest/util/floor/FloorGeneratorAstana48.java
Update floor map to v8 diagram.
> Floor map v8

- Resolver/src/org/icpc/tools/resolver/Resolver.java
> Fix --singleStep without argument

- CDS/WebContent/WEB-INF/jsps/login.jsp
> Add toggle to show password for CDS login

- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
- ContestModel/src/org/icpc/tools/contest/model/ITeam.java
- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Team.java
Watch the file system and check for new / updated / deleted file references on the CDS, and update the contest accordingly.
> Reload file references in CDS

- CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java
Update cache before checking download; handle changed files differently from deleted
> Fix modified file ref handling

- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
- ContestModel/src/org/icpc/tools/contest/model/ISubmission.java
- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Submission.java
Strip file references and only serve remote + local content Add support for dynamic updating of submission files and reactions
> Fix duplicate logo file references

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
When there are more than 10 files changed at a time, the message is shortened to a summary.
> Reduce log messages on file change

- CDS/WebContent/WEB-INF/jsps/layout/footer.jsp
> Check if people are still logged in regularly

- CDS/src/org/icpc/tools/cds/video/ReactionVideoRecorder.java
Remove custom handling to find reaction videos (which was looking for the wrong path) and just let the attachLocal find them.
> Fix check for existing reaction videos

- CDS/WebContent/WEB-INF/jsps/countdown-control.jsp
- CDS/src/org/icpc/tools/cds/presentations/PropertyServlet.java
- PresContest/src/META-INF/presentations.xml
A new form in the web admin to set the team id or label, and finished support for sending properties.
> CDS support for team detail presentation

- PresContest/scripts/client.bat
- PresContest/scripts/client.sh
- PresContest/scripts/standalone.bat
- PresContest/scripts/standalone.sh
- Resolver/scripts/resolver.bat
- Resolver/scripts/resolver.sh
It's 2024, let the presentations have 4Gb max.
> Increase presentation memory

- ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
When the CMS started exporting contest archives I had to rewrite the prior logic that pulled from the CMS file attachment format, and the last piece that I hadn't updated was team photos. This removes the old CMS-folder-structure team photo logic and reuses the same contest format function we do for logos and person photos.
While I was doing that I fixed a few other things:
- Stop warning when team or person photos don't have transparency (code was there for logos).
- Fix out of date class header.
- Remove the MAX_IMAGE_SIZE image generation. It was there for a couple cases where we've had logos that were >4000px, but it is now already handled by generating a 1080p (desktop) logo.
> Add back support for team photos to image generator

- ContestModel/src/org/icpc/tools/contest/model/internal/Ranking.java
- PresAdmin/src/org/icpc/tools/presentation/admin/internal/ClientsControl.java
- PresAdmin/src/org/icpc/tools/presentation/admin/internal/PresentationInfoListControl.java
- PresAdmin/src/org/icpc/tools/presentation/admin/internal/View.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TeamTileHelper.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/tile/TileScoreboardPresentation.java
I have the Java validation set fairly high in Eclipse, and it is complaining about a few things in these files:
- removes unused imports
- makes a private method static
- adds a missing option to a case statement
- applies some missing tabs/alignment in these files... plus other formatting
> Code cleanup

- CDS/WebContent/WEB-INF/jsps/layout/head.jsp
- CDS/src/org/icpc/tools/cds/service/ErrorService.java
I'm moving the CDS up to a recent WLP and Jakarta spec level. This involves a lot of import renaming, updated features, and a few other changes, but once I had done all those... it wouldn't start. This commit just covers some basic refactoring/cleanup that can be applied now although it isn't required until later.
> Pre-Jakarta cleanup

- .github/workflows/builder.yml
- build/builder.Dockerfile
This will push a new builder image when the Dockerfile changes on `main`.
> Auto build Builder container on changes

- BalloonUtility/README.md
- Resolver/README.md
Noticed two really out of date Java versions, update to the correct minimum.
> Update Java version in readmes

- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
- ContestModel/src/org/icpc/tools/contest/model/IOrganization.java
- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Organization.java
- ContestModel/src/org/icpc/tools/contest/model/internal/account/PublicContest.java
Add support for country subdivisions as per the draft spec.
> Add country subdivision support

- .github/workflows/builder.yml
- build/builder.Dockerfile
Going to try switching back to a webprofile WLP (and 2 months newer), since it is working locally but the switch seems to be where the build broke.
Also fix action description.
> Fix WLP build

- CDS/src/org/icpc/tools/cds/service/ContestRESTService.java
> fix: update /api spec version to draft

- BalloonUtility/BalloonUtility.iml
- CDS/CDS.iml
- CoachView/CoachView.iml
- ContestModel/ContestModel.iml
- ContestUtil/ContestUtil.iml
- PresAdmin/PresAdmin.iml
- PresContest/PresContest.iml
- PresCore/PresCore.iml
- ProblemSet/ProblemSet.iml
- Resolver/Resolver.iml
- SWTLauncher/SWTLauncher.iml
@vmcj requested these, and they don't hurt.
> Add IntelliJ IML's

- ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
It was already implied that this should be implemented and it makes doing the logo updates slightly easier.
> Explicit log wrong logo's to missing-data.tsv

- ContestUtil/src/org/icpc/tools/contest/util/ImagesGenerator.java
This code exists since the initial code but is currently not used.
> Remove unused code

- ContestUtil/ContestUtil.iml
I did not build all targets yet so we might need more changes.
> Update Idea config for new dependencies

- CDS/WebContent/js/contest.js
- ContestModel/.classpath
- ContestUtil/src/org/icpc/tools/contest/util/StreamTest.java
contest.js - remove unused var and add _ to unused params .classpath - SVG needs to be exported for SVG util to work StreamTest - previous commit used spaces instead of tabs
> Minor cleanup

- CDS/src/org/icpc/tools/cds/web/TeamPDFService.java
Minor alignment and layout issues of team printout based on feedback at finals.
> Team printout alignment

- CDS/src/org/icpc/tools/cds/web/TeamPDFService.java
Also fix issue with `null` team name.
> Fix PDF UTF 8 rendering

- PresAdmin/src/org/icpc/tools/presentation/admin/internal/ClientsControl.java
Presentation client thumbnails were being generated on any thread, but SWT doesn't appear to allow this anymore, and it caused invalid thread access / no thumbnail in the admin. This changes it to generate the images on the SWT thread.
> Resize admin thumbnails in SWT thread

- ContestModel/src/org/icpc/tools/contest/model/IAward.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Award.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolutionUtil.java
- ContestModel/src/org/icpc/tools/contest/model/resolver/ResolverLogic.java
- PresContest/src/org/icpc/tools/presentation/contest/internal/presentations/MessagePresentation.java
- Resolver/src/org/icpc/tools/resolver/ResolverUI.java
Allows 'after awards' to be simple messages using the message presentation.
> Resolver message presentation

- ContestModel/src/org/icpc/tools/contest/model/feed/DiskContestSource.java
- ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java
Found and fixed a couple more places where file reference tags weren't being updated, and moved it all to one method in FileReference.
> Update file reference tags consistently

- CDS/src/org/icpc/tools/cds/util/PlaybackContest.java
- ContestModel/src/org/icpc/tools/contest/model/IProblem.java
- ContestModel/src/org/icpc/tools/contest/model/internal/Problem.java
Add attachments to problems as per https://github.com/icpc/ccs-specs/pull/226.
> Add problem attachment support
